export interface Country {
  f: string;
  n: string;
  c: string;
}

export const COUNTRIES: Country[] = [
  {f:'🇦🇫',n:'Afghanistan',c:'+93'},{f:'🇦🇱',n:'Albania',c:'+355'},{f:'🇩🇿',n:'Algeria',c:'+213'},
  {f:'🇦🇩',n:'Andorra',c:'+376'},{f:'🇦🇴',n:'Angola',c:'+244'},{f:'🇦🇷',n:'Argentina',c:'+54'},
  {f:'🇦🇲',n:'Armenia',c:'+374'},{f:'🇦🇺',n:'Australia',c:'+61'},{f:'🇦🇹',n:'Austria',c:'+43'},
  {f:'🇦🇿',n:'Azerbaijan',c:'+994'},{f:'🇧🇭',n:'Bahrain',c:'+973'},{f:'🇧🇩',n:'Bangladesh',c:'+880'},
  {f:'🇧🇪',n:'Belgium',c:'+32'},{f:'🇧🇯',n:'Benin',c:'+229'},{f:'🇧🇴',n:'Bolivia',c:'+591'},
  {f:'🇧🇦',n:'Bosnia',c:'+387'},{f:'🇧🇼',n:'Botswana',c:'+267'},{f:'🇧🇷',n:'Brazil',c:'+55'},
  {f:'🇧🇫',n:'Burkina Faso',c:'+226'},{f:'🇧🇮',n:'Burundi',c:'+257'},{f:'🇨🇲',n:'Cameroon',c:'+237'},
  {f:'🇨🇦',n:'Canada',c:'+1'},{f:'🇨🇻',n:'Cape Verde',c:'+238'},{f:'🇨🇫',n:'Central African Rep.',c:'+236'},
  {f:'🇹🇩',n:'Chad',c:'+235'},{f:'🇨🇱',n:'Chile',c:'+56'},{f:'🇨🇳',n:'China',c:'+86'},
  {f:'🇨🇴',n:'Colombia',c:'+57'},{f:'🇰🇲',n:'Comoros',c:'+269'},{f:'🇨🇩',n:'Congo (DRC)',c:'+243'},
  {f:'🇨🇬',n:'Congo (Rep.)',c:'+242'},{f:'🇨🇷',n:'Costa Rica',c:'+506'},{f:'🇨🇮',n:"Côte d'Ivoire",c:'+225'},
  {f:'🇭🇷',n:'Croatia',c:'+385'},{f:'🇨🇾',n:'Cyprus',c:'+357'},{f:'🇨🇿',n:'Czech Republic',c:'+420'},
  {f:'🇩🇰',n:'Denmark',c:'+45'},{f:'🇩🇯',n:'Djibouti',c:'+253'},{f:'🇩🇴',n:'Dominican Republic',c:'+1'},
  {f:'🇪🇨',n:'Ecuador',c:'+593'},{f:'🇪🇬',n:'Egypt',c:'+20'},{f:'🇸🇻',n:'El Salvador',c:'+503'},
  {f:'🇬🇶',n:'Equatorial Guinea',c:'+240'},{f:'🇪🇷',n:'Eritrea',c:'+291'},{f:'🇪🇪',n:'Estonia',c:'+372'},
  {f:'🇪🇹',n:'Ethiopia',c:'+251'},{f:'🇫🇮',n:'Finland',c:'+358'},{f:'🇫🇷',n:'France',c:'+33'},
  {f:'🇬🇦',n:'Gabon',c:'+241'},{f:'🇬🇲',n:'Gambia',c:'+220'},{f:'🇬🇪',n:'Georgia',c:'+995'},
  {f:'🇩🇪',n:'Germany',c:'+49'},{f:'🇬🇭',n:'Ghana',c:'+233'},{f:'🇬🇷',n:'Greece',c:'+30'},
  {f:'🇬🇹',n:'Guatemala',c:'+502'},{f:'🇬🇳',n:'Guinea',c:'+224'},{f:'🇭🇹',n:'Haiti',c:'+509'},
  {f:'🇭🇳',n:'Honduras',c:'+504'},{f:'🇭🇺',n:'Hungary',c:'+36'},{f:'🇮🇸',n:'Iceland',c:'+354'},
  {f:'🇮🇳',n:'India',c:'+91'},{f:'🇮🇩',n:'Indonesia',c:'+62'},{f:'🇮🇷',n:'Iran',c:'+98'},
  {f:'🇮🇶',n:'Iraq',c:'+964'},{f:'🇮🇪',n:'Ireland',c:'+353'},{f:'🇮🇱',n:'Israel',c:'+972'},
  {f:'🇮🇹',n:'Italy',c:'+39'},{f:'🇯🇲',n:'Jamaica',c:'+1'},{f:'🇯🇵',n:'Japan',c:'+81'},
  {f:'🇯🇴',n:'Jordan',c:'+962'},{f:'🇰🇿',n:'Kazakhstan',c:'+7'},{f:'🇰🇪',n:'Kenya',c:'+254'},
  {f:'🇰🇼',n:'Kuwait',c:'+965'},{f:'🇰🇬',n:'Kyrgyzstan',c:'+996'},{f:'🇱🇦',n:'Laos',c:'+856'},
  {f:'🇱🇻',n:'Latvia',c:'+371'},{f:'🇱🇧',n:'Lebanon',c:'+961'},{f:'🇱🇸',n:'Lesotho',c:'+266'},
  {f:'🇱🇷',n:'Liberia',c:'+231'},{f:'🇱🇾',n:'Libya',c:'+218'},{f:'🇱🇹',n:'Lithuania',c:'+370'},
  {f:'🇱🇺',n:'Luxembourg',c:'+352'},{f:'🇲🇬',n:'Madagascar',c:'+261'},{f:'🇲🇼',n:'Malawi',c:'+265'},
  {f:'🇲🇾',n:'Malaysia',c:'+60'},{f:'🇲🇻',n:'Maldives',c:'+960'},{f:'🇲🇱',n:'Mali',c:'+223'},
  {f:'🇲🇹',n:'Malta',c:'+356'},{f:'🇲🇷',n:'Mauritania',c:'+222'},{f:'🇲🇺',n:'Mauritius',c:'+230'},
  {f:'🇲🇽',n:'Mexico',c:'+52'},{f:'🇲🇩',n:'Moldova',c:'+373'},{f:'🇲🇳',n:'Mongolia',c:'+976'},
  {f:'🇲🇦',n:'Morocco',c:'+212'},{f:'🇲🇿',n:'Mozambique',c:'+258'},{f:'🇲🇲',n:'Myanmar',c:'+95'},
  {f:'🇳🇦',n:'Namibia',c:'+264'},{f:'🇳🇵',n:'Nepal',c:'+977'},{f:'🇳🇱',n:'Netherlands',c:'+31'},
  {f:'🇳🇿',n:'New Zealand',c:'+64'},{f:'🇳🇮',n:'Nicaragua',c:'+505'},{f:'🇳🇪',n:'Niger',c:'+227'},
  {f:'🇳🇬',n:'Nigeria',c:'+234'},{f:'🇳🇴',n:'Norway',c:'+47'},{f:'🇴🇲',n:'Oman',c:'+968'},
  {f:'🇵🇰',n:'Pakistan',c:'+92'},{f:'🇵🇦',n:'Panama',c:'+507'},{f:'🇵🇬',n:'Papua New Guinea',c:'+675'},
  {f:'🇵🇾',n:'Paraguay',c:'+595'},{f:'🇵🇪',n:'Peru',c:'+51'},{f:'🇵🇭',n:'Philippines',c:'+63'},
  {f:'🇵🇱',n:'Poland',c:'+48'},{f:'🇵🇹',n:'Portugal',c:'+351'},{f:'🇶🇦',n:'Qatar',c:'+974'},
  {f:'🇷🇴',n:'Romania',c:'+40'},{f:'🇷🇺',n:'Russia',c:'+7'},{f:'🇷🇼',n:'Rwanda',c:'+250'},
  {f:'🇸🇦',n:'Saudi Arabia',c:'+966'},{f:'🇸🇳',n:'Senegal',c:'+221'},{f:'🇷🇸',n:'Serbia',c:'+381'},
  {f:'🇸🇱',n:'Sierra Leone',c:'+232'},{f:'🇸🇬',n:'Singapore',c:'+65'},{f:'🇸🇰',n:'Slovakia',c:'+421'},
  {f:'🇸🇮',n:'Slovenia',c:'+386'},{f:'🇸🇴',n:'Somalia',c:'+252'},{f:'🇿🇦',n:'South Africa',c:'+27'},
  {f:'🇸🇸',n:'South Sudan',c:'+211'},{f:'🇪🇸',n:'Spain',c:'+34'},{f:'🇱🇰',n:'Sri Lanka',c:'+94'},
  {f:'🇸🇩',n:'Sudan',c:'+249'},{f:'🇸🇪',n:'Sweden',c:'+46'},{f:'🇨🇭',n:'Switzerland',c:'+41'},
  {f:'🇸🇾',n:'Syria',c:'+963'},{f:'🇹🇼',n:'Taiwan',c:'+886'},{f:'🇹🇿',n:'Tanzania',c:'+255'},
  {f:'🇹🇭',n:'Thailand',c:'+66'},{f:'🇹🇬',n:'Togo',c:'+228'},{f:'🇹🇳',n:'Tunisia',c:'+216'},
  {f:'🇹🇷',n:'Turkey',c:'+90'},{f:'🇺🇬',n:'Uganda',c:'+256'},{f:'🇺🇦',n:'Ukraine',c:'+380'},
  {f:'🇦🇪',n:'United Arab Emirates',c:'+971'},{f:'🇬🇧',n:'United Kingdom',c:'+44'},
  {f:'🇺🇸',n:'United States',c:'+1'},{f:'🇺🇾',n:'Uruguay',c:'+598'},{f:'🇺🇿',n:'Uzbekistan',c:'+998'},
  {f:'🇻🇪',n:'Venezuela',c:'+58'},{f:'🇻🇳',n:'Vietnam',c:'+84'},{f:'🇾🇪',n:'Yemen',c:'+967'},
  {f:'🇿🇲',n:'Zambia',c:'+260'},{f:'🇿🇼',n:'Zimbabwe',c:'+263'}
];
