// Autogenerated from original project data
export interface IndustryDetail {
  eye: string;
  emoji?: string;
  h1: string;
  sub: string;
  problems?: string[];
  buildIntro?: string;
  buildAssets?: string[];
  serviceGrid?: Array<{ id: string; ico: string; n: string; d: string }>;
  ctaLabel?: string;
  funnel?: string[];
  techStack?: Array<{ l: string; it: string[] }>;
  kpis?: string[];
  faqs?: Array<{ q: string; a: string }>;
  relatedServices?: string[];
  relatedIndustries?: string[];
}

export const INDUSTRIES_DATA: Record<string, IndustryDetail> = {
  "law": {
    "eye": "DIGITAL MARKETING FOR LAW FIRMS",
    "emoji": "⚖️",
    "h1": "Attract more qualified clients with proven law firm marketing.",
    "sub": "Dominate local search in your practice area, build the authority that turns searches into consultations and outrank competing firms — without wasting budget on clicks that never convert.",
    "ctaLabel": "Get Started",
    "problems": [
      "Low visibility for high-value practice area keywords",
      "Weak Google Business Profile performance",
      "Expensive PPC without call or form tracking",
      "Poor consultation follow-up after a lead comes in",
      "Thin practice area pages that fail to build trust",
      "Reputation and review gaps compared with competing firms"
    ],
    "buildIntro": "Marketing does not work alone for a law firm — a ranking keyword with no call tracking or a Google Ad with no CRM follow-up both leak revenue. We pair practice-area marketing with the landing pages, intake automation and reporting that turn search visibility into booked consultations.",
    "buildAssets": [
      "Practice area landing pages for each legal specialty",
      "Call tracking and form tracking across every channel",
      "Lead intake automation with CRM pipeline",
      "Review and reputation management workflow",
      "Compliance-friendly, trust-building ad copy",
      "A consultation-request analytics dashboard"
    ],
    "serviceGrid": [
      {
        "id": "localseo",
        "ico": "📍",
        "n": "Local SEO for Attorneys",
        "d": "Dominate Google Maps and local search for high-value practice area keywords — criminal defense, personal injury, family law, immigration and more."
      },
      {
        "id": "gbp",
        "ico": "📌",
        "n": "Google Business Profile",
        "d": "Professionally managed GBP that drives phone calls and consultations from Google Maps — where most local legal searches begin."
      },
      {
        "id": "geo",
        "ico": "🤖",
        "n": "GEO / AEO — AI Search",
        "d": "Get your firm recommended in ChatGPT and Google AI answers when people ask for attorneys near them — the visibility most law firms haven't addressed yet."
      },
      {
        "id": "content",
        "ico": "✍️",
        "n": "Legal Content Marketing",
        "d": "YMYL-compliant legal content that demonstrates expertise, builds trust and ranks for the informational queries your potential clients research before hiring an attorney."
      },
      {
        "id": "sem",
        "ico": "💰",
        "n": "Legal Google Ads",
        "d": "High-intent Google Ads campaigns capturing searchers with urgent legal needs — with compliant ad copy and landing pages optimized for consultation bookings."
      },
      {
        "id": "cro",
        "ico": "📈",
        "n": "Law Firm Website CRO",
        "d": "Convert more website visitors into consultation bookings — optimizing intake forms, click-to-call buttons and the trust signals hesitant prospects need to take action."
      }
    ],
    "funnel": [
      "Search Visibility",
      "Practice Area Landing Page",
      "Consultation Form / Call",
      "CRM Pipeline",
      "Automated Follow-Up",
      "Review Request",
      "Retargeting"
    ],
    "techStack": [
      {
        "l": "Platforms & CMS",
        "it": [
          "WordPress",
          "Webflow",
          "Custom websites"
        ]
      },
      {
        "l": "Tracking & Automation",
        "it": [
          "Call tracking",
          "GA4",
          "GTM",
          "CRM intake pipeline"
        ]
      },
      {
        "l": "Engagement Tools",
        "it": [
          "Live chat / AI intake chatbot",
          "Calendly-style booking",
          "Review request automation"
        ]
      }
    ],
    "kpis": [
      "Consultation requests",
      "Phone calls",
      "Cost per lead",
      "Form submissions",
      "Google Maps ranking",
      "Practice area keyword growth",
      "Review volume and rating"
    ],
    "faqs": [
          {
                "q": "How can a law firm generate more qualified consultation requests?",
                "a": "We combine practice-area SEO, local search, conversion-focused landing pages, paid search and structured intake follow-up. Success should be measured by qualified enquiries and signed matters—not simply website traffic, impressions or unfiltered lead volume."
          },
          {
                "q": "Should a law firm invest in SEO, Google Ads or Local Services Ads?",
                "a": "The right combination depends on the practice area, location, competition, budget and eligibility. SEO builds long-term visibility, while Google Ads and eligible Local Services Ads can capture people actively searching for legal assistance. We evaluate each channel according to qualified-case potential."
          },
          {
                "q": "How does local SEO help law firms attract clients?",
                "a": "Local SEO helps a firm appear when prospective clients search for a lawyer in a specific city or service area. We optimize eligible Google Business Profiles, location pages, directory information, reviews and practice-area content while following Google’s rules for firms, practitioners and multiple offices."
          },
          {
                "q": "How do you create legal marketing content without making misleading claims?",
                "a": "We create factual, clearly written content that explains services, legal processes and common client questions without promising outcomes. Final legal claims, jurisdiction-specific information, disclaimers and professional-conduct requirements should be reviewed and approved by the law firm."
          },
          {
                "q": "Can digital marketing improve a law firm’s client-intake conversion rate?",
                "a": "Yes. Marketing performance often depends on what happens after an enquiry is received. We can improve forms, call routing, appointment scheduling, CRM workflows and follow-up automation so prospective clients receive timely responses and are directed to the appropriate practice team."
          },
          {
                "q": "How do you track a legal enquiry from its source to a signed client?",
                "a": "We can connect call tracking, website forms, advertising platforms, analytics and the firm’s CRM or intake system. This allows the firm to evaluate which campaigns, keywords and practice areas generate qualified enquiries, consultations and signed matters while protecting sensitive client information."
          },
          {
                "q": "Can a law firm appear in ChatGPT, Google AI Overviews and other AI answers?",
                "a": "Yes and we can improve eligibility by publishing accurate practice-area answers, strengthening the firm’s entity information, building location authority and ensuring important pages are crawlable. Traditional SEO, trustworthy content and consistent business information remain essential."
          },
          {
                "q": "How should law firms manage online reviews ethically?",
                "a": "We can create a policy-compliant review process that invites genuine clients to share feedback without incentives or pressure. Review requests and responses must protect confidentiality, avoid discussing case details and comply with the professional rules governing the firm’s jurisdiction."
          },
          {
                "q": "How should a law firm determine its digital marketing budget?",
                "a": "The budget should reflect the firm’s practice areas, target locations, competition, average matter value, growth capacity and intake performance. We assess where opportunities are being lost before recommending how much should go toward advertising, SEO, content, conversion improvements and tracking."
          },
          {
                "q": "How long does law firm SEO take to produce qualified enquiries?",
                "a": "SEO normally develops gradually because authority, local visibility and content performance must build over time. Paid campaigns may produce faster market data, while organic growth usually compounds over several months. We report early indicators separately from qualified consultations and signed-client outcomes."
          }
    ],
    "relatedServices": [
      "localseo",
      "sem",
      "crm"
    ],
    "relatedIndustries": [
      "realestate",
      "healthcare",
      "fintech"
    ]
  },
  "ecommerce": {
    "eye": "ECOMMERCE GROWTH AGENCY",
    "emoji": "🛒",
    "h1": "Full-funnel e-commerce marketing that grows revenue, not just traffic.",
    "sub": "Product SEO, Google Shopping, Meta ads, Amazon, email flows and CRO — we grow e-commerce revenue across Shopify, WooCommerce and Amazon, globally.",
    "ctaLabel": "Get Started",
    "problems": [
      "Traffic without sales",
      "Poor product page conversion rates",
      "Abandoned carts going unrecovered",
      "Weak product feed setup hurting Shopping performance",
      "High and rising ad costs",
      "Low repeat purchase rate",
      "No email or SMS automation",
      "Poor attribution across paid and organic channels"
    ],
    "buildIntro": "Driving traffic is only half the system — without cart recovery automation, accurate attribution and a conversion-optimized product page, that traffic leaks revenue at every step. We build the full stack: acquisition, conversion and retention working together.",
    "buildAssets": [
      "Cart recovery and lifecycle email/SMS flows",
      "Product feed setup for Shopping & Performance Max",
      "Conversion-optimized product page templates",
      "Cross-channel attribution and analytics setup",
      "Review generation and UGC collection system",
      "An AI product recommendation system"
    ],
    "serviceGrid": [
      {
        "id": "ecoseo",
        "ico": "🛒",
        "n": "E-Commerce SEO",
        "d": "Product page SEO, category optimization and organic product discovery — driving purchase-intent traffic that converts to revenue."
      },
      {
        "id": "fbads",
        "ico": "📣",
        "n": "Meta Ads for E-commerce",
        "d": "Prospecting, retargeting and dynamic product ads on Facebook and Instagram — full-funnel Meta strategy optimized for purchase ROAS."
      },
      {
        "id": "emailauto",
        "ico": "🔄",
        "n": "E-commerce Email Flows",
        "d": "Abandoned cart, welcome series, post-purchase and winback flows — the email automations that recover and multiply e-commerce revenue."
      },
      {
        "id": "amazonseo",
        "ico": "📦",
        "n": "Amazon SEO & Ads",
        "d": "Product listing optimization and Amazon Ads management — dominating the world's largest marketplace for your product category."
      },
      {
        "id": "cro",
        "ico": "📈",
        "n": "Ecommerce CRO",
        "d": "A/B testing, checkout optimization and UX improvements — converting more of your existing traffic into completed purchases without increasing ad spend."
      },
      {
        "id": "ecomdev",
        "ico": "💻",
        "n": "Ecommerce Development",
        "d": "Shopify and WooCommerce builds and rebuilds engineered for conversion, speed and search visibility from day one."
      }
    ],
    "funnel": [
      "Paid Ads / SEO",
      "Product Page",
      "Cart Recovery",
      "Email & SMS Automation",
      "Review Request",
      "Retargeting",
      "Repeat Purchase"
    ],
    "techStack": [
      {
        "l": "Platforms",
        "it": [
          "Shopify",
          "WooCommerce",
          "BigCommerce",
          "Custom builds"
        ]
      },
      {
        "l": "Automation & Email",
        "it": [
          "Klaviyo",
          "Mailchimp",
          "Cart recovery flows"
        ]
      },
      {
        "l": "Tracking & Feeds",
        "it": [
          "Google Merchant Center",
          "GA4 Ecommerce",
          "Meta Pixel & Conversions API"
        ]
      }
    ],
    "kpis": [
      "Revenue",
      "Conversion rate",
      "Average order value",
      "Customer acquisition cost",
      "Return on ad spend",
      "Cart recovery rate",
      "Repeat purchase rate",
      "Email revenue"
    ],
    "faqs": [
          {
                "q": "How can an ecommerce store increase profitable sales rather than just traffic?",
                "a": "We connect customer acquisition, conversion optimization and retention instead of treating them as separate campaigns. The strategy focuses on qualified traffic, conversion rate, acquisition cost, product margin, repeat purchases and customer lifetime value—not visits alone."
          },
          {
                "q": "Which marketing channels are best for an ecommerce business?",
                "a": "The right channels depend on the products, margins, average order value, audience and existing demand. We may combine SEO, Google Shopping, paid social, email, SMS, marketplace marketing and retargeting based on where customers discover and purchase the products."
          },
          {
                "q": "How can product pages and checkout conversion rates be improved?",
                "a": "We examine product information, images, pricing, trust signals, reviews, page speed, mobile usability, shipping information and checkout friction. We then prioritise and test changes that make it easier for customers to understand the offer and complete a purchase."
          },
          {
                "q": "How can abandoned-cart automation recover lost ecommerce sales?",
                "a": "Abandoned-cart workflows remind shoppers about unfinished purchases through email, SMS or approved messaging channels. We segment messages according to customer behaviour and use product reminders, support information and appropriate incentives without creating excessive or intrusive communication."
          },
          {
                "q": "Can you fix Google Merchant Center and Shopping-feed problems?",
                "a": "Yes. We can review product titles, descriptions, identifiers, pricing, availability, images, landing pages and policy-related feed errors. Correct product data helps Google understand the catalogue and reduces inconsistencies between the website, feed and advertising campaigns."
          },
          {
                "q": "Can you market our website alongside Amazon and other marketplaces?",
                "a": "Yes. We can coordinate the owned ecommerce store with relevant marketplaces and social-commerce channels. The strategy considers inventory, pricing, attribution, fulfilment and customer ownership so the channels support one another rather than competing without a clear plan."
          },
          {
                "q": "How should ecommerce marketing performance be measured?",
                "a": "We evaluate revenue together with gross margin, customer acquisition cost, conversion rate, average order value, repeat-purchase rate and customer lifetime value. Return on advertising spend is useful, but it should not be considered without product costs, discounts, refunds and fulfilment expenses."
          },
          {
                "q": "How can AI improve ecommerce marketing and personalisation?",
                "a": "AI can support product recommendations, customer segmentation, search, campaign analysis, forecasting and service automation. We use it where it improves relevance or efficiency while maintaining human review, accurate product information, appropriate consent and responsible use of customer data."
          },
          {
                "q": "How can an online store increase customer retention and repeat purchases?",
                "a": "We can build post-purchase communication, replenishment reminders, personalised recommendations, loyalty programmes, win-back campaigns and customer-service workflows. Retention begins with the buying and fulfilment experience, so marketing cannot compensate for poor product quality or delivery."
          },
          {
                "q": "How do you scale ecommerce advertising without reducing profitability?",
                "a": "We scale gradually using product-level margins, audience quality, creative performance, conversion data and inventory availability. Budgets should increase only when the store can maintain an acceptable acquisition cost and fulfil additional orders without damaging the customer experience."
          }
    ],
    "relatedServices": [
      "ecoseo",
      "fbads",
      "cro"
    ],
    "relatedIndustries": [
      "saas",
      "game",
      "course"
    ]
  },
  "saas": {
    "eye": "SAAS & TECH STARTUP MARKETING",
    "emoji": "💻",
    "h1": "SaaS marketing that drives signups, reduces churn and grows MRR.",
    "sub": "Product-led SEO, demand generation, GEO/AEO for AI visibility, LinkedIn Ads and conversion optimization — specialized marketing for SaaS products at every growth stage.",
    "ctaLabel": "Get Started",
    "problems": [
      "Unclear product positioning",
      "Low demo bookings",
      "Weak product-led SEO",
      "High paid acquisition costs",
      "Low trial-to-paid conversion",
      "No onboarding automation",
      "Poor founder-led content distribution",
      "Weak investor and market visibility"
    ],
    "buildIntro": "A SaaS funnel breaks down wherever marketing and product hand off — a strong landing page with no demo-booking system, or paid traffic with no onboarding automation, both cap growth. We build the acquisition, conversion and activation system as one connected pipeline.",
    "buildAssets": [
      "A demo-booking and free-trial funnel",
      "CRM integration with lead-to-demo tracking",
      "Email onboarding and activation sequences",
      "An AI chatbot for demo qualification",
      "A knowledge base / help center setup",
      "A pipeline and trial-to-paid analytics dashboard"
    ],
    "serviceGrid": [
      {
        "id": "seo",
        "ico": "🔍",
        "n": "Product-Led SEO",
        "d": "Programmatic SEO, comparison pages, integration pages and use-case content — the SEO strategies that drive organic signups for SaaS products at scale."
      },
      {
        "id": "geo",
        "ico": "🤖",
        "n": "GEO / AEO for SaaS",
        "d": "Get your SaaS product recommended in ChatGPT, Gemini and Perplexity when users ask for tool recommendations in your category."
      },
      {
        "id": "linkedinads",
        "ico": "💼",
        "n": "LinkedIn Ads & Demand Gen",
        "d": "Thought leadership ads, lead gen forms and retargeting reaching decision-makers and champions within target company accounts."
      },
      {
        "id": "content",
        "ico": "✍️",
        "n": "SaaS Content Marketing",
        "d": "Bottom-of-funnel content, comparison pages, integration guides and thought leadership — content that captures high-intent buyers comparing solutions."
      },
      {
        "id": "crm",
        "ico": "⚙️",
        "n": "Marketing Automation",
        "d": "Trial nurture sequences, MQL scoring, product-qualified lead workflows and revenue attribution — connecting marketing to pipeline accurately."
      },
      {
        "id": "cro",
        "ico": "📈",
        "n": "Trial & Demo CRO",
        "d": "Optimize free trial signup pages, demo request flows and onboarding — improving activation rate and trial-to-paid conversion simultaneously."
      }
    ],
    "funnel": [
      "Organic / Paid Discovery",
      "Landing Page",
      "Demo or Trial Signup",
      "Onboarding Automation",
      "Activation",
      "Trial-to-Paid Conversion",
      "Expansion"
    ],
    "techStack": [
      {
        "l": "Landing & Product Pages",
        "it": [
          "SaaS landing pages",
          "Webflow",
          "Next.js"
        ]
      },
      {
        "l": "Demo & Onboarding",
        "it": [
          "Demo booking systems",
          "CRM integration",
          "Email onboarding automation"
        ]
      },
      {
        "l": "AI & Analytics",
        "it": [
          "AI chatbot for demo qualification",
          "Product analytics dashboards",
          "API/platform integration"
        ]
      }
    ],
    "kpis": [
      "Demo bookings",
      "Trial signups",
      "Activated users",
      "Cost per acquisition",
      "Lead-to-demo rate",
      "Trial-to-paid conversion",
      "Organic signups",
      "Pipeline value"
    ],
    "faqs": [
          {
                "q": "How can a SaaS company generate more qualified demos or trial sign-ups?",
                "a": "We align search, paid acquisition, content, landing pages and retargeting with the problems experienced by the ideal customer. Campaigns are measured by qualified trials, activated users, demos, sales opportunities and paying customers rather than clicks or form submissions alone."
          },
          {
                "q": "Should a SaaS company use a product-led, sales-led or hybrid growth model?",
                "a": "The appropriate model depends on product complexity, price, target customer and the assistance required before purchase. We help determine whether prospects should begin with self-service access, book a sales demonstration or move through a combination of both experiences."
          },
          {
                "q": "Can you market a SaaS product before it launches?",
                "a": "Yes. Pre-launch marketing can validate positioning, develop a waitlist, attract beta users and collect feedback before significant acquisition spending begins. We can create landing pages, early-access campaigns, founder content, audience research and nurture sequences around the product roadmap."
          },
          {
                "q": "How can a SaaS company reduce customer acquisition cost without lowering lead quality?",
                "a": "We examine targeting, positioning, creative, landing-page conversion, sales qualification and activation—not advertising costs in isolation. Reducing wasted demand and improving conversion between each funnel stage can lower acquisition cost without filling the pipeline with unsuitable prospects."
          },
          {
                "q": "What is product-led SEO?",
                "a": "Product-led SEO creates useful pages around the problems, use cases, integrations, comparisons and workflows the software solves. Instead of attracting unrelated traffic, it connects search intent to product value and directs suitable visitors toward a trial, demo or relevant feature."
          },
          {
                "q": "How can a SaaS product appear in AI-generated recommendations and comparisons?",
                "a": "We improve the product’s factual web presence through clear use-case pages, comparison content, documentation, customer evidence and consistent company information. No agency controls AI recommendations, but authoritative, crawlable and specific content gives search and AI systems stronger information to evaluate."
          },
          {
                "q": "How can marketing improve trial-to-paid conversion?",
                "a": "We analyse signup friction, onboarding, activation events, lifecycle communication and the point where users first experience meaningful value. Email, in-app messaging, retargeting and sales assistance can then be aligned with the behaviours that indicate purchase intent or disengagement."
          },
          {
                "q": "How do you connect SaaS marketing with CRM and product analytics?",
                "a": "We can connect advertising, website analytics, product events and CRM stages so the customer journey is measured beyond the first conversion. This helps identify which channels generate activated users, qualified opportunities, subscriptions and retained revenue."
          },
          {
                "q": "Which metrics matter most in SaaS marketing?",
                "a": "Relevant metrics may include customer acquisition cost, activation rate, trial-to-paid conversion, qualified pipeline, monthly or annual recurring revenue, payback period, lifetime value and churn. The exact measurement framework depends on whether the product is trial-led, demo-led, self-service or enterprise-focused."
          },
          {
                "q": "Do B2B and B2C SaaS products require different marketing strategies?",
                "a": "Yes. B2B SaaS often involves longer buying cycles, multiple decision-makers, demonstrations and account-based targeting. B2C SaaS usually requires faster onboarding, scalable acquisition, strong product experience and retention. We adapt the funnel and measurement model to the actual customer journey. ________________"
          }
    ],
    "relatedServices": [
      "linkedinads",
      "landing",
      "geo"
    ],
    "relatedIndustries": [
      "fintech",
      "ecommerce",
      "game"
    ]
  },
  "game": {
    "eye": "APP & GAME MARKETING AGENCY",
    "emoji": "🎮",
    "h1": "Launch your game or app to the audience it deserves.",
    "sub": "Steam wishlist campaigns, App Store Optimization, TikTok influencer seeding and mobile user acquisition — specialist game and app marketing for indie studios, publishers and mobile-first developers.",
    "ctaLabel": "Get Started",
    "problems": [
      "Low app store or Steam visibility",
      "Expensive user acquisition",
      "Weak pre-launch audience",
      "Poor retention after install",
      "No community built before launch",
      "Weak creative testing process",
      "Poor tracking between ad click, install and in-app action",
      "No plan for ratings and reviews"
    ],
    "buildIntro": "A great trailer with no wishlist tracking, or a paid install campaign with no retention plan, both waste budget — launches succeed when pre-launch audience building, store optimization and post-launch retention are planned as one system, not separate efforts.",
    "buildAssets": [
      "A pre-launch waitlist or wishlist funnel",
      "Firebase / app event tracking setup",
      "Push notification and re-engagement strategy",
      "App store screenshot and creative testing",
      "A Discord or community setup",
      "An in-app analytics dashboard"
    ],
    "serviceGrid": [
      {
        "id": "game",
        "ico": "🎮",
        "n": "Game Marketing",
        "d": "Pre-launch momentum, influencer seeding, community management and review campaigns — the complete game launch marketing system."
      },
      {
        "id": "steam",
        "ico": "🕹️",
        "n": "Steam Marketing",
        "d": "Steam page optimization, wishlist campaigns, Reddit community seeding and launch day execution — maximizing the algorithm-critical launch window."
      },
      {
        "id": "appmarketing",
        "ico": "📲",
        "n": "App Store Optimization",
        "d": "ASO for iOS and Android — keyword optimization, screenshot A/B testing and rating strategy to improve organic app store discovery."
      },
      {
        "id": "tiktok",
        "ico": "🎵",
        "n": "TikTok Game Marketing",
        "d": "Short-form game content, TikTok gaming influencer seeding and paid campaigns — reaching the platform where gaming audiences discover new titles."
      },
      {
        "id": "influencer",
        "ico": "⭐",
        "n": "Gaming Influencer Marketing",
        "d": "Vetted gaming content creators from micro to mega across YouTube, TikTok and Twitch — genre-matched, performance-tracked campaigns."
      },
      {
        "id": "redditmarketing",
        "ico": "🟠",
        "n": "Reddit Gaming Communities",
        "d": "Authentic Reddit strategy for gaming subreddits — community building, AMAs and organic SEO content that drives Steam traffic."
      }
    ],
    "funnel": [
      "Landing Page / Waitlist",
      "Influencer & Community Traffic",
      "Store Listing (App Store / Steam)",
      "Install or Wishlist Tracking",
      "Onboarding",
      "Retention Campaigns",
      "Community Growth"
    ],
    "techStack": [
      {
        "l": "Store & Listing Tools",
        "it": [
          "App Store Connect",
          "Google Play Console",
          "Steamworks"
        ]
      },
      {
        "l": "Tracking & Analytics",
        "it": [
          "Firebase Analytics",
          "AppsFlyer",
          "App event tracking"
        ]
      },
      {
        "l": "Engagement",
        "it": [
          "Push notification strategy",
          "Discord setup",
          "Email onboarding"
        ]
      }
    ],
    "kpis": [
      "App installs",
      "Cost per install",
      "Steam wishlists",
      "App store ranking",
      "Retention rate",
      "Review volume",
      "Community growth",
      "Ad ROAS",
      "Launch day traffic"
    ],
    "faqs": [
          {
                "q": "When should marketing begin for a new app or game?",
                "a": "Marketing should normally begin before release so positioning, audiences, store pages, tracking and creative assets can be tested. For games, this may include a Steam page, playable demo, wishlist strategy and creator outreach; for mobile apps, it may include pre-registration and beta acquisition."
          },
          {
                "q": "How can a game increase Steam wishlists before launch?",
                "a": "We combine an optimised Steam page with trailers, screenshots, demos, creator outreach, community activity, events and trackable campaigns. Wishlist growth should be evaluated by traffic source and audience quality rather than treated as a single isolated number."
          },
          {
                "q": "What is App Store Optimisation, and how does it increase installs?",
                "a": "App Store Optimisation improves how an app or game is discovered and presented in Apple’s App Store and Google Play. It includes keyword research, titles, descriptions, screenshots, preview videos, ratings, localisation and conversion testing within the rules of each store."
          },
          {
                "q": "How do you track app installs and user acquisition accurately?",
                "a": "We connect store-console data, analytics events, advertising platforms and an appropriate mobile measurement system. Because privacy protections limit user-level tracking, performance should be assessed using approved attribution methods, aggregated reporting and post-install behaviour."
          },
          {
                "q": "What determines a realistic cost per install or cost per Steam wishlist?",
                "a": "Cost depends on the platform, country, genre, audience, creative quality, store-page conversion and competition. We establish a working benchmark through controlled testing and assess cost alongside retention, engagement and monetisation rather than choosing the cheapest install or wishlist."
          },
          {
                "q": "Can gaming influencers and content creators help promote a launch?",
                "a": "Yes, when creator audiences and content styles fit the game. We evaluate platform, genre alignment, audience quality, engagement and previous sponsored content before outreach. Performance can be tracked through links, codes, wishlists, installs, engagement and attributable sales where data permits."
          },
          {
                "q": "Is Steam Next Fest suitable for every PC game?",
                "a": "No. It is most useful when the game has a polished demo, a clear store page and enough marketing activity to bring players into the event. We assess development readiness, timing, genre, wishlist goals and the campaign plan before recommending participation."
          },
          {
                "q": "Should a mobile game use a soft launch before global release?",
                "a": "A soft launch can test onboarding, technical stability, monetisation, creative performance and player retention in a controlled market. The findings help determine whether the product and acquisition model are ready to scale or require further development."
          },
          {
                "q": "Can marketing improve retention after an app or game launches?",
                "a": "Yes, although retention also depends heavily on the product experience. We can support onboarding, lifecycle messaging, push notifications, community management, retargeting, content updates and live-operations communication based on how users behave after installation."
          },
          {
                "q": "How does marketing differ for mobile apps, mobile games and PC games?",
                "a": "Mobile apps often focus on utility, subscriptions and activation; mobile games add creative testing, retention and monetisation; PC games rely more heavily on Steam visibility, wishlists, demos, communities and creators. We build the strategy around the platform and revenue model."
          }
    ],
    "relatedServices": [
      "game",
      "steam",
      "mobileapp"
    ],
    "relatedIndustries": [
      "course",
      "saas",
      "ecommerce"
    ]
  },
  "course": {
    "eye": "COURSE & EDUCATION MARKETING",
    "emoji": "🎓",
    "h1": "Fill your courses with students — month after month, consistently.",
    "sub": "Student acquisition systems for course creators and online educators — YouTube SEO, Udemy optimization, paid ads and automated email funnels that generate consistent monthly enrolments.",
    "ctaLabel": "Get Started",
    "problems": [
      "Weak course positioning",
      "Low student enrollment",
      "No course sales funnel",
      "Poor landing page conversion",
      "No webinar or launch system",
      "Weak YouTube discovery",
      "No email nurture sequence",
      "Poor student review strategy"
    ],
    "buildIntro": "Great course content with no sales funnel behind it still struggles to enroll students consistently — we build the landing page, email nurture and webinar system around your content so enrolment doesn't depend on a single launch spike.",
    "buildAssets": [
      "A course landing page built for conversion",
      "A webinar funnel setup",
      "Email launch sequence automation",
      "LMS / payment integration",
      "A student onboarding system",
      "An AI chatbot for common course FAQs"
    ],
    "serviceGrid": [
      {
        "id": "course",
        "ico": "🎓",
        "n": "Course Promotion",
        "d": "Full course marketing system — Udemy SEO, YouTube organic strategy, paid campaigns and email launch funnels that drive consistent student enrolments."
      },
      {
        "id": "videoseo",
        "ico": "🎬",
        "n": "YouTube SEO for Educators",
        "d": "YouTube channel optimization, video SEO and content strategy — turning your teaching content into an organic student acquisition machine."
      },
      {
        "id": "ytads",
        "ico": "▶️",
        "n": "YouTube Ads for Courses",
        "d": "In-stream and discovery ads targeting viewers of competing courses and relevant educational content — driving immediate enrolments."
      },
      {
        "id": "emailauto",
        "ico": "🔄",
        "n": "Course Launch Email Systems",
        "d": "Waitlist sequences, launch week emails, early bird campaigns and post-launch nurture — maximizing revenue from every course launch."
      },
      {
        "id": "seo",
        "ico": "🔍",
        "n": "Google SEO for Educators",
        "d": "Ranking for high-intent educational queries — capturing students actively searching for the skill your course teaches."
      },
      {
        "id": "content",
        "ico": "✍️",
        "n": "Educational Content Marketing",
        "d": "Blog, podcast and free content strategy that builds authority in your subject area — attracting your ideal student through genuine expertise demonstration."
      }
    ],
    "funnel": [
      "YouTube / SEO Discovery",
      "Lead Magnet / Waitlist",
      "Webinar or Landing Page",
      "Email Launch Sequence",
      "Enrollment",
      "Student Onboarding",
      "Review & Referral"
    ],
    "techStack": [
      {
        "l": "Funnel & Pages",
        "it": [
          "Course landing pages",
          "Webinar funnel setup",
          "Email automation"
        ]
      },
      {
        "l": "Platforms",
        "it": [
          "Udemy",
          "Teachable",
          "Kajabi",
          "Coursera"
        ]
      },
      {
        "l": "Support Tools",
        "it": [
          "LMS integration",
          "Payment integration",
          "AI chatbot for course FAQs"
        ]
      }
    ],
    "kpis": [
      "Student enrollments",
      "Cost per enrollment",
      "Webinar registrations",
      "Email list growth",
      "Course conversion rate",
      "Revenue per launch",
      "Student reviews",
      "Repeat course purchases"
    ],
    "faqs": [
          {
                "q": "How can a course creator attract more qualified students?",
                "a": "We begin with the course outcome, ideal student and problem being solved. Search, YouTube, social content, partnerships, email marketing and paid campaigns can then direct suitable prospects into a structured enrolment journey instead of sending general traffic directly to checkout."
          },
          {
                "q": "Do I need a large audience before launching an online course?",
                "a": "No. A smaller relevant audience can be more valuable than a large disengaged following. Early demand can be developed through pilot cohorts, lead magnets, workshops, communities, partnerships and direct audience research before investing heavily in advertising."
          },
          {
                "q": "What should an effective course sales funnel include?",
                "a": "A course funnel normally includes audience discovery, a useful lead magnet or introductory lesson, email nurturing, a sales page, checkout, follow-up and student onboarding. The funnel should explain the transformation, suitability and learning experience—not merely list course modules."
          },
          {
                "q": "Should a course use a live launch or an evergreen enrolment funnel?",
                "a": "Live launches create concentrated attention, interaction and deadlines, while evergreen funnels allow students to enrol throughout the year. We may recommend proving the course and messaging through a live launch before automating a funnel that has not yet demonstrated demand."
          },
          {
                "q": "Can webinars and free workshops increase course enrolments?",
                "a": "Yes. A focused workshop allows prospective students to experience the instructor’s teaching before purchasing. We can develop registration pages, reminders, presentation flow, replay communication, sales follow-up and retargeting for live or established evergreen webinars."
          },
          {
                "q": "Do YouTube, Meta and Google Ads work for selling courses?",
                "a": "They can work when the offer, audience and funnel are already clear. YouTube supports educational discovery, Google captures existing demand and Meta can introduce the course to relevant audiences. Cold traffic should usually be nurtured rather than sent directly to an untested checkout page."
          },
          {
                "q": "Why is an email list important for course marketing?",
                "a": "An email list gives course creators a direct way to educate prospects, announce launches and continue conversations without depending entirely on social algorithms. We can build lead-capture, welcome, webinar, launch, abandoned-checkout and re-engagement sequences around the student journey."
          },
          {
                "q": "Can you promote courses hosted on Udemy, Teachable, Kajabi or a custom website?",
                "a": "Yes. The strategy changes according to the platform’s ownership, tracking, pricing and communication limitations. Marketplace courses may rely more on platform discovery, reviews and volume, while owned platforms provide greater control over customer data, funnels, pricing and email nurturing."
          },
          {
                "q": "How should course-marketing success be measured?",
                "a": "We consider lead cost, webinar registration and attendance, sales-page conversion, cost per enrolment, revenue, refunds and student retention. Completion, satisfaction and referrals also matter because sustainable education marketing depends on delivering the promised learning value."
          },
          {
                "q": "How do you market a course without making unrealistic outcome claims?",
                "a": "We focus messaging on the curriculum, learning experience, instructor expertise, suitable audience and achievable skills. Income, career or performance claims should be supported by evidence, properly qualified and reviewed so marketing does not promise results that depend on factors outside the course."
          }
    ],
    "relatedServices": [
      "course",
      "ytads",
      "landing"
    ],
    "relatedIndustries": [
      "game",
      "saas",
      "nonprofit"
    ]
  },
  "realestate": {
    "eye": "REAL ESTATE MARKETING",
    "emoji": "🏠",
    "h1": "Generate consistent buyer and seller leads for your real estate business.",
    "sub": "Local SEO, Google Maps domination, Google Ads lead generation and real estate website development — marketing systems that generate consistent buyer and seller leads for agents, brokerages and developers.",
    "ctaLabel": "Get Started",
    "problems": [
      "Low local visibility",
      "Property listings not converting",
      "Weak follow-up with buyers and sellers",
      "No CRM pipeline for leads",
      "High cost per lead",
      "Weak neighborhood content",
      "Poor retargeting after property views",
      "Low trust signals and reviews"
    ],
    "buildIntro": "A property listing that ranks well but has no CRM pipeline behind it loses leads to slow follow-up — we connect local visibility, lead capture and automated follow-up so buyer and seller inquiries get a fast, consistent response every time.",
    "buildAssets": [
      "Landing pages for buyers, sellers, investors and renters",
      "CRM and lead follow-up automation",
      "Appointment / viewing booking setup",
      "WhatsApp or SMS lead response system",
      "An AI chatbot for property inquiries",
      "Retargeting for property viewers"
    ],
    "serviceGrid": [
      {
        "id": "localseo",
        "ico": "📍",
        "n": "Local SEO for Real Estate",
        "d": "Dominate Google Search and Maps for \"real estate agent [city]\", \"homes for sale [neighborhood]\" and related high-intent local property keywords."
      },
      {
        "id": "gbp",
        "ico": "📌",
        "n": "Google Business Profile",
        "d": "GBP optimization and management that drives calls and directions from Google Maps — often the first touch point for buyers and sellers researching local agents."
      },
      {
        "id": "sem",
        "ico": "💰",
        "n": "Google Ads Lead Generation",
        "d": "Targeted Google Ads capturing buyers and sellers at the moment of intent — with landing pages optimized for consultation bookings."
      },
      {
        "id": "fbads",
        "ico": "📣",
        "n": "Meta Ads for Real Estate",
        "d": "Facebook and Instagram campaigns for property listings, open house promotion and agent brand building with detailed geographic targeting."
      },
      {
        "id": "webdev",
        "ico": "🌐",
        "n": "Real Estate Website Development",
        "d": "Real estate websites built for SEO, speed and lead capture — converting visitors into consultation bookings and property enquiries."
      },
      {
        "id": "content",
        "ico": "✍️",
        "n": "Real Estate Content Marketing",
        "d": "Neighborhood guides, market reports and buyer/seller guides — content that ranks for local property queries and establishes your authority."
      }
    ],
    "funnel": [
      "Google / Social Discovery",
      "Property Landing Page",
      "Lead Form",
      "CRM Pipeline",
      "Automated Follow-Up",
      "Viewing Booking",
      "Retargeting"
    ],
    "techStack": [
      {
        "l": "Website & Listings",
        "it": [
          "Real estate landing pages",
          "IDX-style listing integration"
        ]
      },
      {
        "l": "Lead Management",
        "it": [
          "CRM setup",
          "Automated follow-up",
          "Appointment booking"
        ]
      },
      {
        "l": "Engagement",
        "it": [
          "WhatsApp / SMS system",
          "AI chatbot for property inquiries"
        ]
      }
    ],
    "kpis": [
      "Buyer leads",
      "Seller leads",
      "Property viewing bookings",
      "Cost per lead",
      "Form submissions",
      "Phone calls",
      "CRM follow-up rate",
      "Retargeting conversion"
    ],
    "faqs": [
          {
                "q": "How can agents, brokerages and property developers generate more qualified leads?",
                "a": "We connect local search, property landing pages, paid campaigns, content and structured follow-up around specific buyer, seller or investor intent. Lead forms should include relevant qualification questions so sales teams can prioritise serious prospects instead of treating every enquiry equally."
          },
          {
                "q": "Are Google Ads, Meta Ads or SEO better for real estate marketing?",
                "a": "Google Ads captures active property-related searches, Meta helps create and nurture demand, and SEO builds longer-term visibility for locations, property types and buyer questions. The strongest combination depends on the project, market, budget, inventory and sales cycle."
          },
          {
                "q": "Should every property development have its own landing page?",
                "a": "Important projects should have focused pages containing location, property type, pricing guidance, amenities, images, availability, credibility information and a clear enquiry action. Dedicated pages create a more relevant experience than sending every advertisement to a general homepage."
          },
          {
                "q": "How can a real estate business appear in local and AI-powered search results?",
                "a": "We strengthen eligible Google Business Profiles, location pages, property information, reviews, structured data and consistent company details. Clear neighbourhood and buyer-focused content also gives traditional search engines and AI systems better factual information about the business and its market."
          },
          {
                "q": "Does a real estate business still need a website if it uses property portals?",
                "a": "Yes. Portals provide exposure, but an owned website gives the business control over branding, enquiries, analytics, content and remarketing. It also allows agents and developers to build long-term search visibility rather than relying entirely on rented marketplace listings."
          },
          {
                "q": "Are there special advertising rules for real estate campaigns?",
                "a": "Yes. Housing advertisements may be subject to platform and jurisdiction-specific restrictions, including limitations on certain audience-targeting methods. We configure campaigns according to applicable advertising policies, while the client remains responsible for reviewing legal and regulatory requirements in its market."
          },
          {
                "q": "Can buyer and seller follow-up be automated through CRM, email or WhatsApp?",
                "a": "Yes. We can route enquiries into a CRM and trigger acknowledgements, reminders, property information, appointment scheduling and nurture sequences. Automation supports the sales team but should allow prompt human intervention when a prospect asks a detailed question or shows strong buying intent."
          },
          {
                "q": "How do you track real estate leads from enquiry to viewing or sale?",
                "a": "We connect advertising and website sources with forms, calls, messaging and CRM stages. This allows the business to evaluate qualified enquiries, appointments, property viewings, negotiations and completed transactions rather than judging marketing solely by cost per lead."
          },
          {
                "q": "How does retargeting work for property buyers with long decision cycles?",
                "a": "Retargeting keeps suitable properties and useful information visible to previous website visitors, video viewers and engaged prospects. Campaigns can be segmented according to viewed locations, property types or funnel stages while respecting advertising consent and housing-policy restrictions."
          },
          {
                "q": "Which metrics matter most in real estate marketing?",
                "a": "Important metrics include qualified enquiries, contact rate, appointment or site-visit rate, cost per qualified lead, pipeline value and completed transactions. Reach and raw lead volume provide context, but they do not show whether marketing is attracting prospects who can and intend to proceed."
          }
    ],
    "relatedServices": [
      "localseo",
      "sem",
      "crm"
    ],
    "relatedIndustries": [
      "law",
      "roofing",
      "healthcare"
    ]
  },
  "roofing": {
    "eye": "ROOFING COMPANY MARKETING",
    "emoji": "🔧",
    "h1": "Generate consistent roofing leads year-round — not just after storms.",
    "sub": "Local SEO, Google Maps Pack, Google Ads and reputation management — marketing systems built specifically for roofing contractors that generate consistent residential and commercial leads in your service area.",
    "ctaLabel": "Get Started",
    "problems": [
      "Weak Google Maps ranking",
      "No dedicated service area pages",
      "Fewer reviews than competitors",
      "No storm-season campaign plan",
      "Poor call tracking",
      "Weak quote request forms",
      "High ad costs without conversion tracking",
      "Slow follow-up after homeowners request estimates"
    ],
    "buildIntro": "A top map-pack ranking with no call tracking, or a quote form with no fast follow-up, both lose jobs to the next roofer the homeowner calls — we connect local visibility, lead capture and rapid follow-up into one system.",
    "buildAssets": [
      "Service area landing pages for every zip code covered",
      "Estimate / quote request forms",
      "Call tracking across every channel",
      "Automated lead follow-up via CRM",
      "Review request automation",
      "A storm-season campaign playbook"
    ],
    "serviceGrid": [
      {
        "id": "localseo",
        "ico": "📍",
        "n": "Local SEO for Roofers",
        "d": "Rank on page 1 of Google for \"roofing company [city]\", \"roof repair near me\" and related high-value keywords in your specific service area."
      },
      {
        "id": "gbp",
        "ico": "📌",
        "n": "Google Business Profile",
        "d": "Map Pack domination — appearing in the top 3 Google Maps results for roofing searches in your city drives the majority of local roofing leads."
      },
      {
        "id": "sem",
        "ico": "💰",
        "n": "Google Ads for Roofers",
        "d": "Targeted Google Ads reaching homeowners actively searching for roofing services — with call extensions and conversion-optimized landing pages."
      },
      {
        "id": "fbads",
        "ico": "📣",
        "n": "Facebook Ads for Roofers",
        "d": "Neighborhood-targeted Facebook campaigns reaching homeowners in your service area — ideal for storm damage follow-up and seasonal promotions."
      },
      {
        "id": "webdev",
        "ico": "🌐",
        "n": "Roofing Website Development",
        "d": "Fast, mobile-first roofing websites with clear service areas, gallery, reviews integration and multiple lead capture points — built to convert visitors into calls."
      },
      {
        "id": "content",
        "ico": "✍️",
        "n": "Roofing Content & Reviews",
        "d": "Blog content targeting local roofing keywords and review generation strategy — building the online authority that drives organic leads year-round."
      }
    ],
    "funnel": [
      "Google Maps / Service Search",
      "Service Area Page",
      "Call or Estimate Form",
      "CRM Pipeline",
      "Fast Follow-Up",
      "Review Request",
      "Retargeting"
    ],
    "techStack": [
      {
        "l": "Website & Pages",
        "it": [
          "Roofing website development",
          "Service area landing pages"
        ]
      },
      {
        "l": "Lead Capture & Tracking",
        "it": [
          "Estimate request forms",
          "Call tracking",
          "CRM setup"
        ]
      },
      {
        "l": "Follow-Up & Reviews",
        "it": [
          "Automated follow-up",
          "Review request automation",
          "Google Maps tracking dashboard"
        ]
      }
    ],
    "kpis": [
      "Phone calls",
      "Quote requests",
      "Cost per roofing lead",
      "Map pack ranking",
      "Service area traffic",
      "Review growth",
      "Form submissions",
      "Booked estimates"
    ],
    "faqs": [
          {
                "q": "What digital marketing works best for roofing companies?",
                "a": "The strongest roofing strategies combine local SEO, Google Business Profile optimization, genuine customer reviews, high-intent Search Ads and Local Services Ads where available. We select the channel mix based on your service area, job types, competition and capacity."
          },
          {
                "q": "How can a roofing company get more qualified local leads?",
                "a": "We target searches connected to real roofing needs, such as roof repair, replacement, inspections, leaks and storm damage. Location targeting, qualifying forms, call tracking and clear service information help reduce irrelevant enquiries."
          },
          {
                "q": "Is SEO or Google Ads better for a roofing company?",
                "a": "Google Ads can produce visibility quickly, while roofing SEO builds sustainable organic and Google Maps visibility over time. Most established roofing companies benefit from using paid search for immediate demand and SEO for long-term lead generation."
          },
          {
                "q": "Are Google Local Services Ads available for roofers?",
                "a": "Roofing companies may qualify for Local Services Ads in supported locations, subject to Google’s category, screening and verification requirements. We can check eligibility, connect the correct Business Profile and configure eligible services and locations."
          },
          {
                "q": "Can roofing service-area pages improve local search visibility?",
                "a": "Yes, when each page contains genuinely useful information about the roofing services, properties and conditions in that location. We avoid near-identical city or postcode pages created only to manipulate rankings."
          },
          {
                "q": "How should roofers market after a hailstorm or severe weather event?",
                "a": "Storm campaigns should be prepared before severe weather occurs and activated only in affected locations. We can combine geo-targeted advertising, storm-damage pages and rapid-response lead routing without using misleading or fear-based claims."
          },
          {
                "q": "How important are Google reviews for roofing companies?",
                "a": "Reviews help homeowners evaluate workmanship, reliability and trust before requesting an inspection or estimate. We help establish ethical review-request and response processes without purchasing reviews or creating false feedback."
          },
          {
                "q": "How do you connect roofing calls and quote requests to signed jobs?",
                "a": "We use campaign tracking, dedicated phone attribution, enquiry forms and CRM stages to follow prospects from their first interaction through inspection, proposal and signed contract. This shows which campaigns generate revenue rather than just calls."
          },
          {
                "q": "Is marketing different for residential and commercial roofing?",
                "a": "Yes. Residential marketing commonly targets urgent homeowner needs and local searches, while commercial roofing involves longer sales cycles, property managers, procurement teams and account-based outreach."
          },
          {
                "q": "How long does roofing marketing take to produce results?",
                "a": "Paid campaigns can begin generating enquiries after setup, approval and optimization, while meaningful organic growth normally takes several months. Timing depends on competition, location, website condition, reputation and marketing investment."
          }
    ],
    "relatedServices": [
      "localseo",
      "gbp",
      "sem"
    ],
    "relatedIndustries": [
      "realestate",
      "healthcare",
      "law"
    ]
  },
  "healthcare": {
    "eye": "HEALTHCARE & WELLNESS MARKETING",
    "emoji": "🏥",
    "h1": "Patient acquisition and practice growth for healthcare providers.",
    "sub": "HIPAA-aware digital marketing for healthcare providers, medical practices and wellness brands — patient acquisition, local SEO and compliant content marketing that builds trust and drives appointments.",
    "ctaLabel": "Get Started",
    "problems": [
      "Low clinic visibility",
      "Weak treatment or service pages",
      "Poor appointment booking conversion",
      "Trust and review gaps",
      "Healthcare content not written with authority",
      "Ad compliance concerns",
      "No patient follow-up system",
      "Poor provider profile pages"
    ],
    "buildIntro": "Healthcare marketing carries a higher trust bar than most industries — a ranking treatment page with a clunky booking flow, or an ad campaign that isn't compliance-aware, both cost patients. We build E-E-A-T-grounded content and booking systems together, with privacy-aware form handling throughout.",
    "buildAssets": [
      "An online appointment booking system",
      "Patient intake forms with privacy-aware handling",
      "Doctor and provider profile pages",
      "Review request automation",
      "Schema and E-E-A-T content structure",
      "An AI chatbot for general FAQs (not medical diagnosis)"
    ],
    "serviceGrid": [
      {
        "id": "localseo",
        "ico": "📍",
        "n": "Healthcare Local SEO",
        "d": "Rank for high-value local medical queries — \"dentist near me\", \"physiotherapist [city]\", \"urgent care [neighborhood]\" — capturing patients at the moment of need."
      },
      {
        "id": "gbp",
        "ico": "📌",
        "n": "Healthcare Google Business Profile",
        "d": "GBP optimization for medical practices — appointment booking integration, service listings, photo management and review acquisition strategy."
      },
      {
        "id": "seo",
        "ico": "🔍",
        "n": "Medical YMYL SEO",
        "d": "E-E-A-T compliant healthcare content that satisfies Google's Your Money Your Life standards — building search visibility without risking ranking penalties."
      },
      {
        "id": "content",
        "ico": "✍️",
        "n": "Healthcare Content Marketing",
        "d": "Medically accurate, privacy-aware content that educates patients, builds practitioner authority and ranks for condition and treatment-related searches."
      },
      {
        "id": "sem",
        "ico": "💰",
        "n": "Healthcare Google Ads",
        "d": "Compliant Google Ads for medical practices — targeted campaigns capturing high-intent patients searching for your specific services in your area."
      },
      {
        "id": "geo",
        "ico": "🤖",
        "n": "Healthcare GEO / AEO",
        "d": "Get your practice recommended in ChatGPT and Google AI answers when patients ask health questions — AI answer engine presence most healthcare providers haven't addressed."
      }
    ],
    "funnel": [
      "Local Search / Maps",
      "Treatment / Service Page",
      "Appointment Booking Form",
      "Patient Intake",
      "Automated Reminder",
      "Review Request",
      "Retargeting"
    ],
    "techStack": [
      {
        "l": "Website & Booking",
        "it": [
          "Clinic website development",
          "Appointment booking system",
          "Patient intake forms"
        ]
      },
      {
        "l": "Trust & Compliance",
        "it": [
          "Privacy-aware form handling",
          "Schema & E-E-A-T content",
          "Review automation"
        ]
      },
      {
        "l": "Engagement",
        "it": [
          "AI chatbot for general FAQs",
          "Analytics dashboard"
        ]
      }
    ],
    "kpis": [
      "Appointments booked",
      "Cost per appointment",
      "Phone calls",
      "Form submissions",
      "Local rankings",
      "Review growth",
      "Treatment page traffic",
      "Patient inquiry rate"
    ],
    "faqs": [
          {
                "q": "How can healthcare providers generate more booked appointments?",
                "a": "We combine treatment-specific pages, local search visibility, appropriate advertising and a streamlined booking journey. Performance is measured through qualified calls and completed bookings rather than website traffic alone."
          },
          {
                "q": "How do you keep healthcare marketing privacy-aware?",
                "a": "We apply data minimization, consent controls and privacy-conscious tracking while avoiding unnecessary collection or disclosure of patient information. The healthcare provider and its legal or compliance advisers retain final approval over regulated requirements."
          },
          {
                "q": "Can healthcare businesses advertise on Google and social platforms?",
                "a": "Many providers can advertise, but restrictions depend on the treatment, product, claim, audience and target country. We review platform policies before launch and avoid prohibited targeting or unsupported medical claims."
          },
          {
                "q": "How do you track healthcare campaigns without exposing patient information?",
                "a": "We configure measurement so advertising platforms do not receive diagnoses, appointment details or other protected information unnecessarily. This can include safer form design, restricted data fields, consent management and carefully controlled analytics."
          },
          {
                "q": "Can an AI chatbot answer patients’ medical questions?",
                "a": "An AI chatbot can handle approved general information, opening hours, service navigation and appointment requests. It should not diagnose conditions, prescribe treatment or replace a qualified professional, and emergency enquiries should be directed to appropriate services."
          },
          {
                "q": "Can you improve a clinic’s visibility in Google and AI-generated answers?",
                "a": "Yes. We strengthen provider and treatment pages, local business information, structured content and trusted references so search systems can understand the organization accurately. Clinical information should be reviewed by an appropriately qualified professional."
          },
          {
                "q": "How should healthcare providers respond to patient reviews?",
                "a": "Responses should remain professional and must not confirm that the reviewer received care or reveal private information. We use neutral responses that acknowledge the feedback and invite the individual to continue the conversation privately."
          },
          {
                "q": "Can you integrate appointment booking and reminder systems?",
                "a": "Yes. We can connect suitable booking, CRM and reminder systems to reduce friction and missed appointments. The selected technology must meet the provider’s privacy, security and consent requirements."
          },
          {
                "q": "Is wellness marketing different from marketing a regulated medical clinic?",
                "a": "Yes. Medical providers usually face stricter requirements around claims, patient information, testimonials and advertising. Wellness brands still need accurate claims and responsible messaging, but their exact obligations depend on the service and jurisdiction."
          },
          {
                "q": "Which metrics should healthcare marketing measure?",
                "a": "Useful metrics include qualified calls, completed bookings, cost per booked appointment, cancellation rates and performance by treatment or location. We avoid treating unqualified form submissions as successful patient acquisition."
          }
    ],
    "relatedServices": [
      "localseo",
      "sem",
      "chatbot"
    ],
    "relatedIndustries": [
      "law",
      "fintech",
      "nonprofit"
    ]
  },
  "restaurant": {
    "eye": "RESTAURANT & FOOD SERVICE MARKETING",
    "emoji": "🍽️",
    "h1": "Fill more tables and grow your restaurant with proven digital marketing.",
    "sub": "Local SEO, Google Maps domination, social media management and reputation management — marketing systems that drive consistent foot traffic, reservations and online orders for restaurants, cafes, bars and food businesses.",
    "ctaLabel": "Get Started",
    "problems": [
      "Weak Google Maps visibility",
      "Menu not optimized for search",
      "Poor online ordering funnel",
      "Low delivery platform visibility",
      "Few reviews compared with competitors",
      "No loyalty or SMS system",
      "Inconsistent social content",
      "No catering or event landing pages"
    ],
    "buildIntro": "Beautiful food photography with no online ordering funnel behind it, or strong Maps visibility with a clunky reservation flow, both leave covers on the table — we connect discovery, ordering and loyalty into one system built around how diners actually search and order.",
    "buildAssets": [
      "An online ordering and reservation system",
      "Menu landing pages optimized for search",
      "A loyalty and SMS promotion system",
      "WhatsApp ordering setup where relevant",
      "Catering and event landing pages",
      "Google Business Profile setup with menu integration"
    ],
    "serviceGrid": [
      {
        "id": "localseo",
        "ico": "📍",
        "n": "Restaurant Local SEO",
        "d": "Dominate \"restaurants near me\", \"best [cuisine] in [city]\" and Google Maps results — capturing hungry customers at the exact moment they search."
      },
      {
        "id": "gbp",
        "ico": "📌",
        "n": "Google Business Profile",
        "d": "Fully optimized GBP with menu integration, photo management, review acquisition and weekly posts — the #1 driver of restaurant foot traffic from Google."
      },
      {
        "id": "smmanage",
        "ico": "📱",
        "n": "Social Media Management",
        "d": "Mouth-watering food photography content, daily posting, community management and influencer seeding — building the social presence that fills seats."
      },
      {
        "id": "fbads",
        "ico": "📣",
        "n": "Facebook & Instagram Ads",
        "d": "Geo-targeted ads reaching hungry local customers — promoting daily specials, events, new menus and online ordering with measurable foot traffic attribution."
      },
      {
        "id": "influencer",
        "ico": "⭐",
        "n": "Food Influencer Marketing",
        "d": "Local food bloggers, Instagram creators and TikTok food accounts driving authentic awareness — the most trusted form of restaurant discovery for new customers."
      },
      {
        "id": "content",
        "ico": "✍️",
        "n": "Reputation Management",
        "d": "Review generation strategy, professional response to all Google and TripAdvisor reviews and reputation monitoring — building the rating that drives reservations."
      }
    ],
    "funnel": [
      "Google Maps / Social Discovery",
      "Menu / Profile View",
      "Reservation or Online Order",
      "Loyalty / SMS Signup",
      "Repeat Visit",
      "Review Request",
      "Referral"
    ],
    "techStack": [
      {
        "l": "Ordering & Booking",
        "it": [
          "Online ordering system",
          "Reservation system",
          "WhatsApp ordering"
        ]
      },
      {
        "l": "Visibility",
        "it": [
          "Google Business Profile setup",
          "Menu landing pages"
        ]
      },
      {
        "l": "Retention",
        "it": [
          "Loyalty and SMS system",
          "Analytics dashboard"
        ]
      }
    ],
    "kpis": [
      "Reservations",
      "Online orders",
      "Delivery orders",
      "Foot traffic",
      "Google Maps views",
      "Review growth",
      "Repeat customers",
      "SMS/email campaign revenue"
    ],
    "faqs": [
          {
                "q": "How can restaurants attract more local customers online?",
                "a": "We improve visibility across Google Search, Maps, menus, reviews, social platforms and ordering channels. The objective is to turn nearby searches into reservations, direct orders, catering enquiries and physical visits."
          },
          {
                "q": "How can a restaurant rank higher on Google Maps?",
                "a": "A complete and accurate Google Business Profile is the foundation. Correct categories, opening hours, menu information, photographs, reviews and consistent location details help Google and customers understand the restaurant."
          },
          {
                "q": "Should a restaurant menu be published as HTML or PDF?",
                "a": "A mobile-friendly HTML menu is normally easier for customers and search engines to use. It can display dishes, descriptions, prices and dietary information clearly, while a PDF may be offered as a secondary download."
          },
          {
                "q": "Can customers order directly through a restaurant’s Google profile?",
                "a": "Where supported, restaurants can add ordering links or connect approved ordering providers to their Google Business Profile. We can organize these links so customers reach the preferred ordering experience with minimal friction."
          },
          {
                "q": "Do Instagram and TikTok generate restaurant sales?",
                "a": "They can when content showcases real dishes, atmosphere, preparation, staff and customer experiences and includes a clear next step. We connect content to reservations, ordering pages or location directions instead of measuring success through views alone."
          },
          {
                "q": "How should restaurants manage negative and positive reviews?",
                "a": "We help restaurants request genuine feedback, respond professionally and identify recurring operational issues. Defensive responses, fake reviews and incentives that distort customer opinion should be avoided."
          },
          {
                "q": "Can you set up restaurant loyalty, email, SMS or WhatsApp campaigns?",
                "a": "Yes. We can create consent-based campaigns for repeat visits, birthday offers, menu launches and inactive-customer reactivation. Messages should remain relevant, reasonably timed and easy to opt out of."
          },
          {
                "q": "Can digital marketing generate catering and private-event enquiries?",
                "a": "Yes. Dedicated catering and event pages can target searches for corporate catering, celebrations, group dining and venue hire. Enquiry forms should capture date, party size, budget and service requirements."
          },
          {
                "q": "How should marketing work for a multi-location restaurant business?",
                "a": "Each location should have accurate profiles, location-specific pages, menus, reviews and reporting. We maintain brand consistency while allowing every branch to target its own neighbourhood and customer demand."
          },
          {
                "q": "How do you know whether restaurant marketing produces actual orders and visits?",
                "a": "We track reservations, direct orders, calls, direction requests, offer redemptions and loyalty activity where the necessary data is available. Reporting separates meaningful restaurant outcomes from impressions and social engagement."
          }
    ],
    "relatedServices": [
      "localseo",
      "smmanage",
      "sms"
    ],
    "relatedIndustries": [
      "realestate",
      "nonprofit",
      "roofing"
    ]
  },
  "nonprofit": {
    "eye": "NONPROFIT & CHARITY MARKETING",
    "emoji": "💛",
    "h1": "Amplify your mission — reach more donors, volunteers and supporters.",
    "sub": "Nonprofit-specific SEO, Google Ad Grants management, social media campaigns and donation funnel optimization — helping nonprofits and charities maximize their digital presence and fundraising impact.",
    "ctaLabel": "Get Started",
    "problems": [
      "Low donation conversion",
      "Weak storytelling",
      "Poor donor retention",
      "No email nurture sequence",
      "Limited campaign visibility",
      "No volunteer recruitment funnel",
      "Weak impact reporting",
      "Poor event promotion"
    ],
    "buildIntro": "Powerful mission storytelling with no donation page optimization, or strong campaign reach with no donor retention follow-up, both leave impact on the table — we connect awareness, conversion and retention into one donor journey.",
    "buildAssets": [
      "Donation landing pages with payment integration",
      "A donor CRM / management integration",
      "Email donor nurture automation",
      "Volunteer sign-up forms",
      "An impact reporting dashboard",
      "An AI chatbot for donor questions"
    ],
    "serviceGrid": [
      {
        "id": "sem",
        "ico": "💰",
        "n": "Google Ad Grants Management",
        "d": "We manage your monthly Google Ad Grants account to drive maximum qualified traffic for donor acquisition, volunteer recruitment and cause awareness."
      },
      {
        "id": "seo",
        "ico": "🔍",
        "n": "Nonprofit SEO",
        "d": "Rank for cause-related search terms, donor intent keywords and volunteer recruitment queries — building organic visibility that compounds over time."
      },
      {
        "id": "content",
        "ico": "✍️",
        "n": "Impact Content Marketing",
        "d": "Storytelling content — impact reports, beneficiary stories, volunteer spotlights — that builds emotional connection and drives recurring donor retention."
      },
      {
        "id": "emailauto",
        "ico": "🔄",
        "n": "Donor Email Automation",
        "d": "Welcome sequences, impact updates, donation reminders and re-engagement campaigns — nurturing one-time donors into recurring supporters automatically."
      },
      {
        "id": "smm",
        "ico": "📱",
        "n": "Social Media for Nonprofits",
        "d": "Mission-driven social media strategy building community, sharing impact stories and mobilizing supporters across Facebook, Instagram, TikTok and LinkedIn."
      },
      {
        "id": "cro",
        "ico": "📈",
        "n": "Donation Page Optimization",
        "d": "A/B testing and CRO for donation pages, volunteer signup forms and event registration — increasing the percentage of visitors who take action."
      }
    ],
    "funnel": [
      "Campaign / PR Visibility",
      "Donation or Volunteer Landing Page",
      "Donation Form / Signup",
      "Donor CRM",
      "Email Nurture",
      "Impact Update",
      "Recurring Donation"
    ],
    "techStack": [
      {
        "l": "Donation & Forms",
        "it": [
          "Donation landing pages",
          "Payment integration",
          "Volunteer sign-up forms"
        ]
      },
      {
        "l": "Donor Management",
        "it": [
          "CRM / donor management integration",
          "Email automation"
        ]
      },
      {
        "l": "Reporting & Engagement",
        "it": [
          "Impact dashboard",
          "AI chatbot for donor questions",
          "Campaign reporting dashboard"
        ]
      }
    ],
    "kpis": [
      "Donations",
      "Donation conversion rate",
      "Donor retention",
      "Volunteer signups",
      "Campaign reach",
      "Email open/click rate",
      "Event registrations",
      "Cost per donor"
    ],
    "faqs": [
          {
                "q": "Which digital marketing channels help nonprofits raise more donations?",
                "a": "Effective nonprofit marketing may combine organic search, Google Ad Grants, paid advertising, email, social media and optimized donation pages. The right combination depends on the organization’s mission, audience, location and fundraising model."
          },
          {
                "q": "What is Google Ad Grants, and does the nonprofit receive cash?",
                "a": "Google Ad Grants provides eligible nonprofits with up to $10,000 per month in in-kind Google Search advertising. It is advertising credit rather than cash, and actual usage depends on relevant search demand and continued policy compliance."
          },
          {
                "q": "Is every nonprofit eligible for Google Ad Grants?",
                "a": "No. The organization must satisfy Google’s current eligibility requirements, complete verification, maintain an appropriate website and follow the program’s policies. Approval and continued participation are controlled by Google."
          },
          {
                "q": "Can Google Ad Grants be used to generate donations?",
                "a": "Yes, eligible organizations can promote mission-related donation and fundraising pages when campaigns and landing pages comply with program policies. We also track conversions so the grant is evaluated through meaningful actions rather than ad clicks alone."
          },
          {
                "q": "Can a nonprofit use paid Google Ads alongside an Ad Grant?",
                "a": "Yes. A standard paid Google Ads account can complement the grant by supporting additional campaign formats, audiences and competitive searches. We keep the objectives and reporting clear so the accounts work together effectively."
          },
          {
                "q": "What makes a nonprofit donation page convert better?",
                "a": "A strong donation page explains the impact of each contribution, establishes trust and makes completing a gift simple on mobile devices. Clear donation amounts, recurring options, secure payment information and minimal form fields reduce friction."
          },
          {
                "q": "How can digital marketing improve donor retention?",
                "a": "We use audience segmentation, welcome journeys, impact updates and appropriate recurring-gift communication to maintain the relationship after the first donation. Retention depends on showing supporters what their contribution helped accomplish."
          },
          {
                "q": "Can you promote volunteer recruitment as well as donations?",
                "a": "Yes. Volunteer campaigns can target people by location, skills, availability or cause interest and send them to dedicated opportunity pages. We measure completed applications and suitable placements rather than page visits alone."
          },
          {
                "q": "Can you support peer-to-peer fundraising campaigns?",
                "a": "Yes. We can develop participant recruitment, campaign pages, supporter toolkits, email journeys and performance tracking. The strategy should make it easy for supporters to create, explain and share their individual fundraising pages."
          },
          {
                "q": "How should a nonprofit measure marketing success?",
                "a": "Important measures can include donor acquisition cost, recurring-donor growth, donation-page conversion, retention, volunteer applications and program registrations. We align reporting with the organization’s mission rather than relying only on reach or impressions."
          }
    ],
    "relatedServices": [
      "email",
      "digitalpr",
      "crm"
    ],
    "relatedIndustries": [
      "healthcare",
      "restaurant",
      "course"
    ]
  },
  "fintech": {
    "eye": "FINANCE & FINTECH MARKETING",
    "emoji": "💰",
    "h1": "Compliant, high-performance digital marketing for finance and fintech brands.",
    "sub": "YMYL-aware SEO, compliant paid advertising, GEO/AEO for AI financial queries and content marketing — driving qualified customer acquisition for banks, fintechs, investment platforms, insurance brands and financial advisors.",
    "ctaLabel": "Get Started",
    "problems": [
      "Low trust in financial offers",
      "Compliance-sensitive messaging constraints",
      "Weak educational content",
      "Expensive lead generation",
      "Poor fintech app visibility",
      "No investor positioning",
      "Weak retargeting and nurture",
      "No structured authority content"
    ],
    "buildIntro": "Financial marketing carries strict compliance and trust requirements most generalist agencies underestimate — a high-ranking page with non-compliant claims, or a strong app install campaign with no secure landing page behind it, both create risk. We build authority content and conversion systems with regulatory-safe messaging from the start.",
    "buildAssets": [
      "Secure, compliance-friendly landing pages",
      "Compliance-friendly form handling",
      "CRM integration for application tracking",
      "App analytics for fintech apps",
      "A trust and credibility content system",
      "An AI chatbot for general product questions"
    ],
    "serviceGrid": [
      {
        "id": "seo",
        "ico": "🔍",
        "n": "YMYL Financial SEO",
        "d": "E-E-A-T compliant SEO for finance — ranking for high-value money and investment keywords while meeting Google's strict Your Money Your Life content standards."
      },
      {
        "id": "geo",
        "ico": "🤖",
        "n": "GEO/AEO for Finance",
        "d": "Get your brand recommended in ChatGPT and Google AI answers when users ask financial questions — the fastest-growing discovery channel for fintech brands."
      },
      {
        "id": "content",
        "ico": "✍️",
        "n": "Financial Content Marketing",
        "d": "Expert financial content — guides, calculators, market commentary and educational resources — building the E-E-A-T signals that Google and AI models reward."
      },
      {
        "id": "linkedinads",
        "ico": "💼",
        "n": "LinkedIn Ads for Fintech",
        "d": "B2B fintech advertising reaching CFOs, finance directors and investment decision-makers — with compliant messaging and high-quality lead generation."
      },
      {
        "id": "sem",
        "ico": "💰",
        "n": "Compliant Google Ads",
        "d": "Certified, policy-compliant Google Ads for financial services — navigating Google's financial product advertising policies to maximize visibility and conversions."
      },
      {
        "id": "crm",
        "ico": "⚙️",
        "n": "Fintech Marketing Automation",
        "d": "Lead nurturing, onboarding sequences, product activation campaigns and lifecycle marketing — converting sign-ups into active, revenue-generating customers."
      }
    ],
    "funnel": [
      "Search / LinkedIn Discovery",
      "Trust / Education Page",
      "Application or Demo Start",
      "CRM Tracking",
      "Compliance-Safe Nurture",
      "Activation",
      "Retargeting"
    ],
    "techStack": [
      {
        "l": "Website & Forms",
        "it": [
          "Fintech website development",
          "Secure landing pages",
          "Compliance-friendly forms"
        ]
      },
      {
        "l": "Tracking & Integration",
        "it": [
          "CRM integration",
          "App analytics",
          "API integration support"
        ]
      },
      {
        "l": "Trust & Engagement",
        "it": [
          "Dashboard reporting",
          "AI chatbot for general product questions"
        ]
      }
    ],
    "kpis": [
      "Qualified finance leads",
      "App installs",
      "Cost per lead",
      "Demo bookings",
      "Application starts",
      "Trust page engagement",
      "Organic traffic",
      "Investor inquiries"
    ],
    "faqs": [
          {
                "q": "Can financial services and fintech companies advertise on Google?",
                "a": "Many can, but eligibility depends on the financial product, target country, licensing status and Google’s current policies. Some advertisers require verification or certification, and campaign approval can never be guaranteed."
          },
          {
                "q": "How do you handle compliance-sensitive financial content?",
                "a": "We use documented review workflows, reliable sources, appropriate disclosures and controlled content versions. The client’s legal or compliance team retains final approval because marketing services do not replace regulatory advice."
          },
          {
                "q": "What should a high-converting finance landing page include?",
                "a": "It should explain the product, intended customer, eligibility, costs, benefits, risks and next step without making misleading promises. Clear disclosures, secure forms and consistent information help prospects make informed decisions."
          },
          {
                "q": "Can you market fintech mobile apps?",
                "a": "Yes. We can combine app-store optimization, compliant acquisition campaigns, search visibility, landing pages, onboarding communication and retention activity. Performance should be measured beyond installs through activation and valuable user actions."
          },
          {
                "q": "How can fintech companies reduce customer acquisition costs?",
                "a": "We improve targeting, landing-page conversion, onboarding and lifecycle communication while removing low-quality traffic. Acquisition cost should be reviewed alongside customer value, retention and risk—not optimized in isolation."
          },
          {
                "q": "How can a finance brand build trust online?",
                "a": "Trust signals include transparent fees, accurate eligibility information, regulatory details, security explanations, identifiable leadership and expert-reviewed educational content. These claims must remain consistent across the website, advertising and third-party profiles."
          },
          {
                "q": "How do you track fintech leads and conversions securely?",
                "a": "We design measurement around necessary business events while limiting unnecessary personal or financial data. Reporting can cover applications, verification, account funding or qualified leads without sending confidential account information to advertising platforms."
          },
          {
                "q": "What are GEO and AEO for financial services?",
                "a": "GEO and AEO improve how clearly search engines and AI systems can understand and reference a financial brand. We focus on factual product information, transparent fees, eligibility, expert-reviewed answers, trusted citations and consistent brand data."
          },
          {
                "q": "Can you improve investor visibility for a fintech company?",
                "a": "Yes. We can support investor-facing content, executive positioning, media outreach and appropriate campaign visibility. Investor communication should remain separate from customer acquisition and comply with applicable securities and promotion rules."
          },
          {
                "q": "Which metrics should a finance or fintech campaign measure?",
                "a": "Depending on the business, useful metrics include qualified applications, verification completion, funded accounts, activated users, retention, customer acquisition cost, lifetime value and qualified B2B pipeline. Impressions and raw leads are supporting indicators, not final outcomes."
          }
    ],
    "relatedServices": [
      "geo",
      "linkedinads",
      "chatbot"
    ],
    "relatedIndustries": [
      "saas",
      "law",
      "healthcare"
    ]
  }
};
