// Autogenerated from original project data
export interface IndustryDetail {
  eye: string;
  emoji?: string;
  h1: string;
  sub: string;
  problems?: string[];
  buildIntro?: string;
  buildAssets?: string[];
  serviceGrid?: Array<{ id: string; ico: string; n: string; d: string }>;
  ctaLabel?: string;
  funnel?: string[];
  techStack?: Array<{ l: string; it: string[] }>;
  kpis?: string[];
  faqs?: Array<{ q: string; a: string }>;
  relatedServices?: string[];
  relatedIndustries?: string[];
}

export const INDUSTRIES_DATA: Record<string, IndustryDetail> = {
  "law": {
    "eye": "DIGITAL MARKETING FOR LAW FIRMS",
    "emoji": "⚖️",
    "h1": "Attract more qualified clients with proven law firm marketing.",
    "sub": "Dominate local search in your practice area, build the authority that turns searches into consultations and outrank competing firms — without wasting budget on clicks that never convert.",
    "ctaLabel": "Get Started",
    "problems": [
      "Low visibility for high-value practice area keywords",
      "Weak Google Business Profile performance",
      "Expensive PPC without call or form tracking",
      "Poor consultation follow-up after a lead comes in",
      "Thin practice area pages that fail to build trust",
      "Reputation and review gaps compared with competing firms"
    ],
    "buildIntro": "Marketing does not work alone for a law firm — a ranking keyword with no call tracking or a Google Ad with no CRM follow-up both leak revenue. We pair practice-area marketing with the landing pages, intake automation and reporting that turn search visibility into booked consultations.",
    "buildAssets": [
      "Practice area landing pages for each legal specialty",
      "Call tracking and form tracking across every channel",
      "Lead intake automation with CRM pipeline",
      "Review and reputation management workflow",
      "Compliance-friendly, trust-building ad copy",
      "A consultation-request analytics dashboard"
    ],
    "serviceGrid": [
      {
        "id": "localseo",
        "ico": "📍",
        "n": "Local SEO for Attorneys",
        "d": "Dominate Google Maps and local search for high-value practice area keywords — criminal defense, personal injury, family law, immigration and more."
      },
      {
        "id": "gbp",
        "ico": "📌",
        "n": "Google Business Profile",
        "d": "Professionally managed GBP that drives phone calls and consultations from Google Maps — where most local legal searches begin."
      },
      {
        "id": "geo",
        "ico": "🤖",
        "n": "GEO / AEO — AI Search",
        "d": "Get your firm recommended in ChatGPT and Google AI answers when people ask for attorneys near them — the visibility most law firms haven't addressed yet."
      },
      {
        "id": "content",
        "ico": "✍️",
        "n": "Legal Content Marketing",
        "d": "YMYL-compliant legal content that demonstrates expertise, builds trust and ranks for the informational queries your potential clients research before hiring an attorney."
      },
      {
        "id": "sem",
        "ico": "💰",
        "n": "Legal Google Ads",
        "d": "High-intent Google Ads campaigns capturing searchers with urgent legal needs — with compliant ad copy and landing pages optimized for consultation bookings."
      },
      {
        "id": "cro",
        "ico": "📈",
        "n": "Law Firm Website CRO",
        "d": "Convert more website visitors into consultation bookings — optimizing intake forms, click-to-call buttons and the trust signals hesitant prospects need to take action."
      }
    ],
    "funnel": [
      "Search Visibility",
      "Practice Area Landing Page",
      "Consultation Form / Call",
      "CRM Pipeline",
      "Automated Follow-Up",
      "Review Request",
      "Retargeting"
    ],
    "techStack": [
      {
        "l": "Platforms & CMS",
        "it": [
          "WordPress",
          "Webflow",
          "Custom websites"
        ]
      },
      {
        "l": "Tracking & Automation",
        "it": [
          "Call tracking",
          "GA4",
          "GTM",
          "CRM intake pipeline"
        ]
      },
      {
        "l": "Engagement Tools",
        "it": [
          "Live chat / AI intake chatbot",
          "Calendly-style booking",
          "Review request automation"
        ]
      }
    ],
    "kpis": [
      "Consultation requests",
      "Phone calls",
      "Cost per lead",
      "Form submissions",
      "Google Maps ranking",
      "Practice area keyword growth",
      "Review volume and rating"
    ],
    "faqs": [
      {
        "q": "How can law firms get more consultation requests?",
        "a": "Consistent consultation growth comes from combining practice-area SEO and Google Business Profile optimization with call/form tracking and fast automated follow-up — visibility alone rarely converts without a tracked intake process behind it."
      },
      {
        "q": "Is SEO important for law firms?",
        "a": "Yes — most prospective clients search Google before contacting a firm, and practice-area SEO plus local SEO determine whether your firm or a competitor shows up first for high-value searches like \"personal injury lawyer near me\"."
      },
      {
        "q": "Should law firms run Google Ads?",
        "a": "Google Ads can deliver fast, high-intent consultation leads for urgent legal needs, but only performs well when paired with call/form tracking and conversion-optimized landing pages — without that, ad spend is hard to attribute or improve."
      },
      {
        "q": "Can you build practice area landing pages?",
        "a": "Yes — dedicated landing pages for each practice area (personal injury, family law, immigration, criminal defense and others) are a core deliverable, built specifically to build trust and convert consultation-intent traffic."
      },
      {
        "q": "How do you track law firm leads?",
        "a": "Call tracking numbers, form tracking and CRM pipeline integration give a full view of every consultation request by source, so spend can be attributed accurately rather than guessed at."
      },
      {
        "q": "Do you handle Google Business Profile management for multiple office locations?",
        "a": "Yes — multi-location law firms are managed with location-specific GBP optimization, citation consistency and local landing pages for each office."
      },
      {
        "q": "How do you write legal marketing content without making unverifiable claims?",
        "a": "We write YMYL-compliant content that demonstrates expertise through process, case-type knowledge and clear explanation of legal concepts — without guaranteeing case outcomes or making claims that could violate bar advertising rules."
      },
      {
        "q": "How long does it take to see results from law firm SEO?",
        "a": "Local SEO and Google Business Profile improvements often show initial movement within 60-90 days, while competitive practice-area keyword rankings typically take 4-6 months to mature."
      },
      {
        "q": "Do you help with online reviews for law firms?",
        "a": "Yes — a structured, compliant review request workflow triggered after positive case milestones is part of the reputation management system we build for law firm clients."
      },
      {
        "q": "Can you work with a solo practice as well as a multi-attorney firm?",
        "a": "Yes — scope and channel mix are tailored to firm size, from solo practitioners focused on one practice area to multi-attorney firms competing across several specialties and locations."
      },
      {
        "q": "Do you require a long-term contract?",
        "a": "No — engagements run month-to-month with no lock-in contract, and we report transparently on consultation requests and pipeline so results, not a contract term, keep you with us."
      }
    ],
    "relatedServices": [
      "localseo",
      "sem",
      "crm"
    ],
    "relatedIndustries": [
      "realestate",
      "healthcare",
      "fintech"
    ]
  },
  "ecommerce": {
    "eye": "ECOMMERCE GROWTH AGENCY",
    "emoji": "🛒",
    "h1": "Full-funnel e-commerce marketing that grows revenue, not just traffic.",
    "sub": "Product SEO, Google Shopping, Meta ads, Amazon, email flows and CRO — we grow e-commerce revenue across Shopify, WooCommerce and Amazon, globally.",
    "ctaLabel": "Get Started",
    "problems": [
      "Traffic without sales",
      "Poor product page conversion rates",
      "Abandoned carts going unrecovered",
      "Weak product feed setup hurting Shopping performance",
      "High and rising ad costs",
      "Low repeat purchase rate",
      "No email or SMS automation",
      "Poor attribution across paid and organic channels"
    ],
    "buildIntro": "Driving traffic is only half the system — without cart recovery automation, accurate attribution and a conversion-optimized product page, that traffic leaks revenue at every step. We build the full stack: acquisition, conversion and retention working together.",
    "buildAssets": [
      "Cart recovery and lifecycle email/SMS flows",
      "Product feed setup for Shopping & Performance Max",
      "Conversion-optimized product page templates",
      "Cross-channel attribution and analytics setup",
      "Review generation and UGC collection system",
      "An AI product recommendation system"
    ],
    "serviceGrid": [
      {
        "id": "ecoseo",
        "ico": "🛒",
        "n": "E-Commerce SEO",
        "d": "Product page SEO, category optimization and organic product discovery — driving purchase-intent traffic that converts to revenue."
      },
      {
        "id": "fbads",
        "ico": "📣",
        "n": "Meta Ads for E-commerce",
        "d": "Prospecting, retargeting and dynamic product ads on Facebook and Instagram — full-funnel Meta strategy optimized for purchase ROAS."
      },
      {
        "id": "emailauto",
        "ico": "🔄",
        "n": "E-commerce Email Flows",
        "d": "Abandoned cart, welcome series, post-purchase and winback flows — the email automations that recover and multiply e-commerce revenue."
      },
      {
        "id": "amazonseo",
        "ico": "📦",
        "n": "Amazon SEO & Ads",
        "d": "Product listing optimization and Amazon Ads management — dominating the world's largest marketplace for your product category."
      },
      {
        "id": "cro",
        "ico": "📈",
        "n": "Ecommerce CRO",
        "d": "A/B testing, checkout optimization and UX improvements — converting more of your existing traffic into completed purchases without increasing ad spend."
      },
      {
        "id": "ecomdev",
        "ico": "💻",
        "n": "Ecommerce Development",
        "d": "Shopify and WooCommerce builds and rebuilds engineered for conversion, speed and search visibility from day one."
      }
    ],
    "funnel": [
      "Paid Ads / SEO",
      "Product Page",
      "Cart Recovery",
      "Email & SMS Automation",
      "Review Request",
      "Retargeting",
      "Repeat Purchase"
    ],
    "techStack": [
      {
        "l": "Platforms",
        "it": [
          "Shopify",
          "WooCommerce",
          "BigCommerce",
          "Custom builds"
        ]
      },
      {
        "l": "Automation & Email",
        "it": [
          "Klaviyo",
          "Mailchimp",
          "Cart recovery flows"
        ]
      },
      {
        "l": "Tracking & Feeds",
        "it": [
          "Google Merchant Center",
          "GA4 Ecommerce",
          "Meta Pixel & Conversions API"
        ]
      }
    ],
    "kpis": [
      "Revenue",
      "Conversion rate",
      "Average order value",
      "Customer acquisition cost",
      "Return on ad spend",
      "Cart recovery rate",
      "Repeat purchase rate",
      "Email revenue"
    ],
    "faqs": [
      {
        "q": "Can you help improve ecommerce sales?",
        "a": "Yes — we combine SEO, paid ads, email/SMS automation and conversion rate optimization into one system, since sales growth rarely comes from a single channel working in isolation."
      },
      {
        "q": "Do you work with Shopify stores?",
        "a": "Yes — Shopify is one of our most-supported platforms, alongside WooCommerce, BigCommerce and custom-built e-commerce sites."
      },
      {
        "q": "What is the best marketing strategy for ecommerce?",
        "a": "It depends on your product, margin and current channel mix — but most e-commerce brands benefit from pairing paid acquisition (Meta, Google Shopping) with cart recovery automation and CRO, since acquisition without retention caps long-term growth."
      },
      {
        "q": "Do you handle abandoned cart emails?",
        "a": "Yes — abandoned cart sequences, alongside welcome series, post-purchase and win-back flows, are a core deliverable for every e-commerce engagement."
      },
      {
        "q": "Can you improve product page conversion rates?",
        "a": "Yes — product page CRO (imagery, copy, trust signals, checkout flow) is assessed and optimized as part of the engagement, often one of the fastest wins available since it doesn't require new traffic."
      },
      {
        "q": "Do you manage Amazon listings alongside our own website?",
        "a": "Yes — Amazon SEO and Ads management run alongside your own store's marketing, with strategy coordinated so the two channels don't cannibalize the same keywords."
      },
      {
        "q": "How do you measure ecommerce marketing ROI?",
        "a": "We track revenue, ROAS, customer acquisition cost and repeat purchase rate as the core metrics, tied directly to GA4 Ecommerce and platform-level attribution rather than vanity traffic numbers."
      },
      {
        "q": "Can you fix our Google Shopping feed?",
        "a": "Yes — product feed audits and optimization for Google Merchant Center are a standard part of getting Shopping and Performance Max campaigns performing."
      },
      {
        "q": "Do you work with stores outside the US?",
        "a": "Yes — we support e-commerce brands worldwide across all markets, including Paystack/Flutterwave payment integration for African markets."
      },
      {
        "q": "How quickly can ecommerce marketing show results?",
        "a": "Paid campaigns can show initial movement within days; SEO and lifecycle email typically take 60-90 days to compound meaningfully — we set a realistic timeline based on your starting point during onboarding."
      },
      {
        "q": "Do you require a long-term contract?",
        "a": "No — engagements are month-to-month with no lock-in contract, reported against revenue and ROAS rather than vanity metrics."
      }
    ],
    "relatedServices": [
      "ecoseo",
      "fbads",
      "cro"
    ],
    "relatedIndustries": [
      "saas",
      "game",
      "course"
    ]
  },
  "saas": {
    "eye": "SAAS & TECH STARTUP MARKETING",
    "emoji": "💻",
    "h1": "SaaS marketing that drives signups, reduces churn and grows MRR.",
    "sub": "Product-led SEO, demand generation, GEO/AEO for AI visibility, LinkedIn Ads and conversion optimization — specialized marketing for SaaS products at every growth stage.",
    "ctaLabel": "Get Started",
    "problems": [
      "Unclear product positioning",
      "Low demo bookings",
      "Weak product-led SEO",
      "High paid acquisition costs",
      "Low trial-to-paid conversion",
      "No onboarding automation",
      "Poor founder-led content distribution",
      "Weak investor and market visibility"
    ],
    "buildIntro": "A SaaS funnel breaks down wherever marketing and product hand off — a strong landing page with no demo-booking system, or paid traffic with no onboarding automation, both cap growth. We build the acquisition, conversion and activation system as one connected pipeline.",
    "buildAssets": [
      "A demo-booking and free-trial funnel",
      "CRM integration with lead-to-demo tracking",
      "Email onboarding and activation sequences",
      "An AI chatbot for demo qualification",
      "A knowledge base / help center setup",
      "A pipeline and trial-to-paid analytics dashboard"
    ],
    "serviceGrid": [
      {
        "id": "seo",
        "ico": "🔍",
        "n": "Product-Led SEO",
        "d": "Programmatic SEO, comparison pages, integration pages and use-case content — the SEO strategies that drive organic signups for SaaS products at scale."
      },
      {
        "id": "geo",
        "ico": "🤖",
        "n": "GEO / AEO for SaaS",
        "d": "Get your SaaS product recommended in ChatGPT, Gemini and Perplexity when users ask for tool recommendations in your category."
      },
      {
        "id": "linkedinads",
        "ico": "💼",
        "n": "LinkedIn Ads & Demand Gen",
        "d": "Thought leadership ads, lead gen forms and retargeting reaching decision-makers and champions within target company accounts."
      },
      {
        "id": "content",
        "ico": "✍️",
        "n": "SaaS Content Marketing",
        "d": "Bottom-of-funnel content, comparison pages, integration guides and thought leadership — content that captures high-intent buyers comparing solutions."
      },
      {
        "id": "crm",
        "ico": "⚙️",
        "n": "Marketing Automation",
        "d": "Trial nurture sequences, MQL scoring, product-qualified lead workflows and revenue attribution — connecting marketing to pipeline accurately."
      },
      {
        "id": "cro",
        "ico": "📈",
        "n": "Trial & Demo CRO",
        "d": "Optimize free trial signup pages, demo request flows and onboarding — improving activation rate and trial-to-paid conversion simultaneously."
      }
    ],
    "funnel": [
      "Organic / Paid Discovery",
      "Landing Page",
      "Demo or Trial Signup",
      "Onboarding Automation",
      "Activation",
      "Trial-to-Paid Conversion",
      "Expansion"
    ],
    "techStack": [
      {
        "l": "Landing & Product Pages",
        "it": [
          "SaaS landing pages",
          "Webflow",
          "Next.js"
        ]
      },
      {
        "l": "Demo & Onboarding",
        "it": [
          "Demo booking systems",
          "CRM integration",
          "Email onboarding automation"
        ]
      },
      {
        "l": "AI & Analytics",
        "it": [
          "AI chatbot for demo qualification",
          "Product analytics dashboards",
          "API/platform integration"
        ]
      }
    ],
    "kpis": [
      "Demo bookings",
      "Trial signups",
      "Activated users",
      "Cost per acquisition",
      "Lead-to-demo rate",
      "Trial-to-paid conversion",
      "Organic signups",
      "Pipeline value"
    ],
    "faqs": [
      {
        "q": "How do SaaS companies get more demo bookings?",
        "a": "Demo bookings improve most reliably through a combination of clear product-led landing pages, retargeting for engaged visitors and LinkedIn demand gen targeting the specific decision-makers and champions inside target accounts."
      },
      {
        "q": "Do you help early-stage startups?",
        "a": "Yes — pre-launch and early-stage SaaS companies are a significant share of our clients, with strategy scoped around limited budget and the need to validate positioning before scaling spend."
      },
      {
        "q": "Can you market a SaaS product before launch?",
        "a": "Yes — pre-launch waitlist funnels, Product Hunt launch support and early content/SEO foundation-building are common starting points before a public launch."
      },
      {
        "q": "Do you build SaaS landing pages?",
        "a": "Yes — conversion-focused landing pages built specifically around demo or trial conversion, with message match to whichever campaign or channel is driving traffic."
      },
      {
        "q": "How do you reduce customer acquisition cost?",
        "a": "CAC reduction usually comes from improving conversion at each funnel stage (landing page, demo booking, trial activation) rather than only optimizing ad bids — we address both the acquisition and conversion sides together."
      },
      {
        "q": "What is product-led SEO?",
        "a": "Product-led SEO targets the specific comparison, integration and use-case searches your ideal buyers run while evaluating tools in your category — content built to convert rather than just rank."
      },
      {
        "q": "Do you help with GEO/AEO so our SaaS product gets recommended by AI tools?",
        "a": "Yes — GEO/AEO optimization is a growing part of SaaS marketing, since buyers increasingly ask ChatGPT or Perplexity for tool recommendations before ever visiting a search engine."
      },
      {
        "q": "Can you help reduce trial-to-paid churn?",
        "a": "Trial-to-paid conversion is improved through onboarding automation, activation-focused email sequences and CRO on the upgrade flow itself — addressed as part of marketing automation rather than left to product alone."
      },
      {
        "q": "Do you work with B2B and B2C SaaS differently?",
        "a": "Yes — B2B SaaS typically leans on LinkedIn, demand gen and longer sales cycles, while B2C SaaS leans more on paid social, SEO and self-serve conversion optimization; strategy is built around your specific buyer."
      },
      {
        "q": "Do you require a long-term contract?",
        "a": "No — month-to-month engagements with no lock-in, reported against pipeline and trial-to-paid metrics rather than vanity traffic."
      },
      {
        "q": "How quickly can SaaS marketing show results?",
        "a": "Paid demand gen can show pipeline movement within weeks; product-led SEO and content typically take 3-6 months to compound — we set a realistic timeline based on your current organic baseline."
      }
    ],
    "relatedServices": [
      "linkedinads",
      "landing",
      "geo"
    ],
    "relatedIndustries": [
      "fintech",
      "ecommerce",
      "game"
    ]
  },
  "game": {
    "eye": "APP & GAME MARKETING AGENCY",
    "emoji": "🎮",
    "h1": "Launch your game or app to the audience it deserves.",
    "sub": "Steam wishlist campaigns, App Store Optimization, TikTok influencer seeding and mobile user acquisition — specialist game and app marketing for indie studios, publishers and mobile-first developers.",
    "ctaLabel": "Get Started",
    "problems": [
      "Low app store or Steam visibility",
      "Expensive user acquisition",
      "Weak pre-launch audience",
      "Poor retention after install",
      "No community built before launch",
      "Weak creative testing process",
      "Poor tracking between ad click, install and in-app action",
      "No plan for ratings and reviews"
    ],
    "buildIntro": "A great trailer with no wishlist tracking, or a paid install campaign with no retention plan, both waste budget — launches succeed when pre-launch audience building, store optimization and post-launch retention are planned as one system, not separate efforts.",
    "buildAssets": [
      "A pre-launch waitlist or wishlist funnel",
      "Firebase / app event tracking setup",
      "Push notification and re-engagement strategy",
      "App store screenshot and creative testing",
      "A Discord or community setup",
      "An in-app analytics dashboard"
    ],
    "serviceGrid": [
      {
        "id": "game",
        "ico": "🎮",
        "n": "Game Marketing",
        "d": "Pre-launch momentum, influencer seeding, community management and review campaigns — the complete game launch marketing system."
      },
      {
        "id": "steam",
        "ico": "🕹️",
        "n": "Steam Marketing",
        "d": "Steam page optimization, wishlist campaigns, Reddit community seeding and launch day execution — maximizing the algorithm-critical launch window."
      },
      {
        "id": "appmarketing",
        "ico": "📲",
        "n": "App Store Optimization",
        "d": "ASO for iOS and Android — keyword optimization, screenshot A/B testing and rating strategy to improve organic app store discovery."
      },
      {
        "id": "tiktok",
        "ico": "🎵",
        "n": "TikTok Game Marketing",
        "d": "Short-form game content, TikTok gaming influencer seeding and paid campaigns — reaching the platform where gaming audiences discover new titles."
      },
      {
        "id": "influencer",
        "ico": "⭐",
        "n": "Gaming Influencer Marketing",
        "d": "Vetted gaming content creators from micro to mega across YouTube, TikTok and Twitch — genre-matched, performance-tracked campaigns."
      },
      {
        "id": "redditmarketing",
        "ico": "🟠",
        "n": "Reddit Gaming Communities",
        "d": "Authentic Reddit strategy for gaming subreddits — community building, AMAs and organic SEO content that drives Steam traffic."
      }
    ],
    "funnel": [
      "Landing Page / Waitlist",
      "Influencer & Community Traffic",
      "Store Listing (App Store / Steam)",
      "Install or Wishlist Tracking",
      "Onboarding",
      "Retention Campaigns",
      "Community Growth"
    ],
    "techStack": [
      {
        "l": "Store & Listing Tools",
        "it": [
          "App Store Connect",
          "Google Play Console",
          "Steamworks"
        ]
      },
      {
        "l": "Tracking & Analytics",
        "it": [
          "Firebase Analytics",
          "AppsFlyer",
          "App event tracking"
        ]
      },
      {
        "l": "Engagement",
        "it": [
          "Push notification strategy",
          "Discord setup",
          "Email onboarding"
        ]
      }
    ],
    "kpis": [
      "App installs",
      "Cost per install",
      "Steam wishlists",
      "App store ranking",
      "Retention rate",
      "Review volume",
      "Community growth",
      "Ad ROAS",
      "Launch day traffic"
    ],
    "faqs": [
      {
        "q": "Can you help increase Steam wishlists?",
        "a": "Yes — Steam page optimization, key art and trailer testing, Reddit/Discord community building and a coordinated Steam Next Fest strategy are all part of how we drive wishlist growth before launch."
      },
      {
        "q": "Do you market mobile apps before launch?",
        "a": "Yes — pre-launch waitlist funnels, organic social seeding and early ASO foundation-building help build an install-ready audience before the app is even live."
      },
      {
        "q": "Do you handle App Store Optimization?",
        "a": "Yes — ASO covering keyword optimization, title/subtitle, screenshots and rating strategy is a core service for both iOS and Android listings."
      },
      {
        "q": "Can you help with gaming influencers?",
        "a": "Yes — we maintain a vetted network of gaming creators across YouTube, TikTok and Twitch, matched to your title's genre and audience rather than picked by follower count alone."
      },
      {
        "q": "How do you track app installs and user acquisition?",
        "a": "Firebase Analytics and AppsFlyer attribution connect ad clicks to installs and in-app events, so spend can be evaluated against actual user behavior rather than install volume alone."
      },
      {
        "q": "Is Steam Next Fest worth participating in for our game?",
        "a": "For most titles without an existing following, yes — Next Fest delivers a concentrated visibility spike to an audience actively looking for new games to wishlist."
      },
      {
        "q": "Do you help with both indie and larger studio titles?",
        "a": "Yes — indie developers make up a significant share of our game marketing clients, with campaign scope built to match realistic indie budgets alongside larger publisher engagements."
      },
      {
        "q": "What is a realistic cost-per-install for mobile games?",
        "a": "CPI varies significantly by genre, platform and geography — we benchmark against your specific category and target markets during strategy rather than quoting an industry-wide average."
      },
      {
        "q": "Can you help with retention after launch, not just acquisition?",
        "a": "Yes — push notification strategy, re-engagement campaigns and onboarding flow optimization are addressed alongside acquisition, since retention is what actually determines long-term revenue."
      },
      {
        "q": "Do you work with both PC/Steam titles and mobile games?",
        "a": "Yes — though the channel mix differs: Steam titles lean on wishlist campaigns and community seeding, while mobile games lean more on ASO and paid UA."
      },
      {
        "q": "Do you require a long-term contract?",
        "a": "No — campaign engagements are scoped around your launch timeline, with month-to-month flexibility once the title is live."
      }
    ],
    "relatedServices": [
      "game",
      "steam",
      "mobileapp"
    ],
    "relatedIndustries": [
      "course",
      "saas",
      "ecommerce"
    ]
  },
  "course": {
    "eye": "COURSE & EDUCATION MARKETING",
    "emoji": "🎓",
    "h1": "Fill your courses with students — month after month, consistently.",
    "sub": "Student acquisition systems for course creators and online educators — YouTube SEO, Udemy optimization, paid ads and automated email funnels that generate consistent monthly enrolments.",
    "ctaLabel": "Get Started",
    "problems": [
      "Weak course positioning",
      "Low student enrollment",
      "No course sales funnel",
      "Poor landing page conversion",
      "No webinar or launch system",
      "Weak YouTube discovery",
      "No email nurture sequence",
      "Poor student review strategy"
    ],
    "buildIntro": "Great course content with no sales funnel behind it still struggles to enroll students consistently — we build the landing page, email nurture and webinar system around your content so enrolment doesn't depend on a single launch spike.",
    "buildAssets": [
      "A course landing page built for conversion",
      "A webinar funnel setup",
      "Email launch sequence automation",
      "LMS / payment integration",
      "A student onboarding system",
      "An AI chatbot for common course FAQs"
    ],
    "serviceGrid": [
      {
        "id": "course",
        "ico": "🎓",
        "n": "Course Promotion",
        "d": "Full course marketing system — Udemy SEO, YouTube organic strategy, paid campaigns and email launch funnels that drive consistent student enrolments."
      },
      {
        "id": "videoseo",
        "ico": "🎬",
        "n": "YouTube SEO for Educators",
        "d": "YouTube channel optimization, video SEO and content strategy — turning your teaching content into an organic student acquisition machine."
      },
      {
        "id": "ytads",
        "ico": "▶️",
        "n": "YouTube Ads for Courses",
        "d": "In-stream and discovery ads targeting viewers of competing courses and relevant educational content — driving immediate enrolments."
      },
      {
        "id": "emailauto",
        "ico": "🔄",
        "n": "Course Launch Email Systems",
        "d": "Waitlist sequences, launch week emails, early bird campaigns and post-launch nurture — maximizing revenue from every course launch."
      },
      {
        "id": "seo",
        "ico": "🔍",
        "n": "Google SEO for Educators",
        "d": "Ranking for high-intent educational queries — capturing students actively searching for the skill your course teaches."
      },
      {
        "id": "content",
        "ico": "✍️",
        "n": "Educational Content Marketing",
        "d": "Blog, podcast and free content strategy that builds authority in your subject area — attracting your ideal student through genuine expertise demonstration."
      }
    ],
    "funnel": [
      "YouTube / SEO Discovery",
      "Lead Magnet / Waitlist",
      "Webinar or Landing Page",
      "Email Launch Sequence",
      "Enrollment",
      "Student Onboarding",
      "Review & Referral"
    ],
    "techStack": [
      {
        "l": "Funnel & Pages",
        "it": [
          "Course landing pages",
          "Webinar funnel setup",
          "Email automation"
        ]
      },
      {
        "l": "Platforms",
        "it": [
          "Udemy",
          "Teachable",
          "Kajabi",
          "Coursera"
        ]
      },
      {
        "l": "Support Tools",
        "it": [
          "LMS integration",
          "Payment integration",
          "AI chatbot for course FAQs"
        ]
      }
    ],
    "kpis": [
      "Student enrollments",
      "Cost per enrollment",
      "Webinar registrations",
      "Email list growth",
      "Course conversion rate",
      "Revenue per launch",
      "Student reviews",
      "Repeat course purchases"
    ],
    "faqs": [
      {
        "q": "How can I get more students for my course?",
        "a": "Consistent enrolment growth comes from combining organic discovery (YouTube SEO, content) with a structured email nurture sequence and a conversion-focused landing page — relying on a single launch spike rarely sustains enrolment month over month."
      },
      {
        "q": "Do you promote Udemy courses?",
        "a": "Yes — Udemy SEO (title, description, category optimization) alongside off-platform traffic strategies is part of how we help Udemy-hosted courses grow enrolment."
      },
      {
        "q": "Can you build a course sales funnel?",
        "a": "Yes — from lead magnet through webinar or landing page to email launch sequence, the full funnel is built and automated as a core deliverable."
      },
      {
        "q": "Do YouTube Ads work for courses?",
        "a": "Yes, particularly when targeted at viewers of competing courses or closely related educational content — in-stream and discovery formats both perform well for course-specific campaigns."
      },
      {
        "q": "Can you help with webinar funnels?",
        "a": "Yes — webinar registration pages, the live or evergreen webinar funnel itself, and the follow-up email sequence are all part of the funnel system we build."
      },
      {
        "q": "Do you work with course creators on platforms other than Udemy?",
        "a": "Yes — Teachable, Kajabi, Coursera, Skillshare and self-hosted course platforms are all supported, with strategy adjusted to each platform's specific discovery mechanics."
      },
      {
        "q": "How important is an email list for course creators?",
        "a": "Very — an owned email list is typically the highest-converting channel for course launches, since it reaches an audience that has already opted in and shown interest."
      },
      {
        "q": "Do I need an existing audience to start?",
        "a": "No — though an existing audience accelerates results, we build acquisition strategy (YouTube SEO, paid ads) specifically designed to generate enrolments for creators starting from zero."
      },
      {
        "q": "Can you help with an evergreen funnel, not just live launches?",
        "a": "Yes — an automated evergreen enrolment funnel running continuously, separate from scheduled live launches, is a common setup for course creators wanting consistent monthly revenue."
      },
      {
        "q": "How do you measure success for course marketing?",
        "a": "Student enrolments, cost per enrolment, webinar registration rate and revenue per launch are the core metrics we track and report against monthly."
      },
      {
        "q": "Do you require a long-term contract?",
        "a": "No — engagements run month-to-month, with launch-specific projects scoped around your actual cohort or launch calendar."
      }
    ],
    "relatedServices": [
      "course",
      "ytads",
      "landing"
    ],
    "relatedIndustries": [
      "game",
      "saas",
      "nonprofit"
    ]
  },
  "realestate": {
    "eye": "REAL ESTATE MARKETING",
    "emoji": "🏠",
    "h1": "Generate consistent buyer and seller leads for your real estate business.",
    "sub": "Local SEO, Google Maps domination, Google Ads lead generation and real estate website development — marketing systems that generate consistent buyer and seller leads for agents, brokerages and developers.",
    "ctaLabel": "Get Started",
    "problems": [
      "Low local visibility",
      "Property listings not converting",
      "Weak follow-up with buyers and sellers",
      "No CRM pipeline for leads",
      "High cost per lead",
      "Weak neighborhood content",
      "Poor retargeting after property views",
      "Low trust signals and reviews"
    ],
    "buildIntro": "A property listing that ranks well but has no CRM pipeline behind it loses leads to slow follow-up — we connect local visibility, lead capture and automated follow-up so buyer and seller inquiries get a fast, consistent response every time.",
    "buildAssets": [
      "Landing pages for buyers, sellers, investors and renters",
      "CRM and lead follow-up automation",
      "Appointment / viewing booking setup",
      "WhatsApp or SMS lead response system",
      "An AI chatbot for property inquiries",
      "Retargeting for property viewers"
    ],
    "serviceGrid": [
      {
        "id": "localseo",
        "ico": "📍",
        "n": "Local SEO for Real Estate",
        "d": "Dominate Google Search and Maps for \"real estate agent [city]\", \"homes for sale [neighborhood]\" and related high-intent local property keywords."
      },
      {
        "id": "gbp",
        "ico": "📌",
        "n": "Google Business Profile",
        "d": "GBP optimization and management that drives calls and directions from Google Maps — often the first touch point for buyers and sellers researching local agents."
      },
      {
        "id": "sem",
        "ico": "💰",
        "n": "Google Ads Lead Generation",
        "d": "Targeted Google Ads capturing buyers and sellers at the moment of intent — with landing pages optimized for consultation bookings."
      },
      {
        "id": "fbads",
        "ico": "📣",
        "n": "Meta Ads for Real Estate",
        "d": "Facebook and Instagram campaigns for property listings, open house promotion and agent brand building with detailed geographic targeting."
      },
      {
        "id": "webdev",
        "ico": "🌐",
        "n": "Real Estate Website Development",
        "d": "Real estate websites built for SEO, speed and lead capture — converting visitors into consultation bookings and property enquiries."
      },
      {
        "id": "content",
        "ico": "✍️",
        "n": "Real Estate Content Marketing",
        "d": "Neighborhood guides, market reports and buyer/seller guides — content that ranks for local property queries and establishes your authority."
      }
    ],
    "funnel": [
      "Google / Social Discovery",
      "Property Landing Page",
      "Lead Form",
      "CRM Pipeline",
      "Automated Follow-Up",
      "Viewing Booking",
      "Retargeting"
    ],
    "techStack": [
      {
        "l": "Website & Listings",
        "it": [
          "Real estate landing pages",
          "IDX-style listing integration"
        ]
      },
      {
        "l": "Lead Management",
        "it": [
          "CRM setup",
          "Automated follow-up",
          "Appointment booking"
        ]
      },
      {
        "l": "Engagement",
        "it": [
          "WhatsApp / SMS system",
          "AI chatbot for property inquiries"
        ]
      }
    ],
    "kpis": [
      "Buyer leads",
      "Seller leads",
      "Property viewing bookings",
      "Cost per lead",
      "Form submissions",
      "Phone calls",
      "CRM follow-up rate",
      "Retargeting conversion"
    ],
    "faqs": [
      {
        "q": "How can real estate agents get more leads?",
        "a": "Lead growth comes from combining strong local visibility (SEO, GBP) with conversion-focused landing pages and fast, automated CRM follow-up — visibility without a tracked follow-up system leaves leads to go cold."
      },
      {
        "q": "Do you create property landing pages?",
        "a": "Yes — dedicated landing pages for buyers, sellers, investors and renters are built to convert each specific audience, rather than sending all traffic to one generic page."
      },
      {
        "q": "Can you run Facebook Ads for real estate?",
        "a": "Yes — geo-targeted Meta campaigns for listings, open houses and agent brand building are a core part of real estate marketing, with detailed local targeting."
      },
      {
        "q": "Do you help with Google ranking for realtors?",
        "a": "Yes — local SEO and Google Business Profile optimization are central to ranking for high-intent searches like \"real estate agent [city]\" and \"homes for sale [neighborhood]\"."
      },
      {
        "q": "Can you automate follow-up with buyers and sellers?",
        "a": "Yes — CRM pipeline setup with automated follow-up sequences ensures every lead is contacted quickly and consistently, rather than depending on manual outreach."
      },
      {
        "q": "Do you work with brokerages as well as individual agents?",
        "a": "Yes — both individual agents and multi-agent brokerages are supported, with strategy and CRM structure scaled to the size of your team."
      },
      {
        "q": "Can you help with neighborhood-specific content?",
        "a": "Yes — neighborhood guides and market report content are built to rank for hyper-local property searches and establish your authority in specific areas."
      },
      {
        "q": "Do you support property developers as well as agents?",
        "a": "Yes — developers marketing new builds or pre-sale units are supported with dedicated landing pages and lead capture systems for project-specific campaigns."
      },
      {
        "q": "How do you handle retargeting for property viewers?",
        "a": "Pixel-based retargeting campaigns target users who viewed specific property listings but didn't convert, keeping that property in front of genuinely interested buyers."
      },
      {
        "q": "How quickly can real estate marketing show results?",
        "a": "Paid lead generation can show movement within days; local SEO ranking improvements typically take 60-90 days to compound — we set expectations based on your specific market during onboarding."
      },
      {
        "q": "Do you require a long-term contract?",
        "a": "No — month-to-month engagements with no lock-in, reported against buyer/seller lead volume and cost per lead."
      }
    ],
    "relatedServices": [
      "localseo",
      "sem",
      "crm"
    ],
    "relatedIndustries": [
      "law",
      "roofing",
      "healthcare"
    ]
  },
  "roofing": {
    "eye": "ROOFING COMPANY MARKETING",
    "emoji": "🔧",
    "h1": "Generate consistent roofing leads year-round — not just after storms.",
    "sub": "Local SEO, Google Maps Pack, Google Ads and reputation management — marketing systems built specifically for roofing contractors that generate consistent residential and commercial leads in your service area.",
    "ctaLabel": "Get Started",
    "problems": [
      "Weak Google Maps ranking",
      "No dedicated service area pages",
      "Fewer reviews than competitors",
      "No storm-season campaign plan",
      "Poor call tracking",
      "Weak quote request forms",
      "High ad costs without conversion tracking",
      "Slow follow-up after homeowners request estimates"
    ],
    "buildIntro": "A top map-pack ranking with no call tracking, or a quote form with no fast follow-up, both lose jobs to the next roofer the homeowner calls — we connect local visibility, lead capture and rapid follow-up into one system.",
    "buildAssets": [
      "Service area landing pages for every zip code covered",
      "Estimate / quote request forms",
      "Call tracking across every channel",
      "Automated lead follow-up via CRM",
      "Review request automation",
      "A storm-season campaign playbook"
    ],
    "serviceGrid": [
      {
        "id": "localseo",
        "ico": "📍",
        "n": "Local SEO for Roofers",
        "d": "Rank on page 1 of Google for \"roofing company [city]\", \"roof repair near me\" and related high-value keywords in your specific service area."
      },
      {
        "id": "gbp",
        "ico": "📌",
        "n": "Google Business Profile",
        "d": "Map Pack domination — appearing in the top 3 Google Maps results for roofing searches in your city drives the majority of local roofing leads."
      },
      {
        "id": "sem",
        "ico": "💰",
        "n": "Google Ads for Roofers",
        "d": "Targeted Google Ads reaching homeowners actively searching for roofing services — with call extensions and conversion-optimized landing pages."
      },
      {
        "id": "fbads",
        "ico": "📣",
        "n": "Facebook Ads for Roofers",
        "d": "Neighborhood-targeted Facebook campaigns reaching homeowners in your service area — ideal for storm damage follow-up and seasonal promotions."
      },
      {
        "id": "webdev",
        "ico": "🌐",
        "n": "Roofing Website Development",
        "d": "Fast, mobile-first roofing websites with clear service areas, gallery, reviews integration and multiple lead capture points — built to convert visitors into calls."
      },
      {
        "id": "content",
        "ico": "✍️",
        "n": "Roofing Content & Reviews",
        "d": "Blog content targeting local roofing keywords and review generation strategy — building the online authority that drives organic leads year-round."
      }
    ],
    "funnel": [
      "Google Maps / Service Search",
      "Service Area Page",
      "Call or Estimate Form",
      "CRM Pipeline",
      "Fast Follow-Up",
      "Review Request",
      "Retargeting"
    ],
    "techStack": [
      {
        "l": "Website & Pages",
        "it": [
          "Roofing website development",
          "Service area landing pages"
        ]
      },
      {
        "l": "Lead Capture & Tracking",
        "it": [
          "Estimate request forms",
          "Call tracking",
          "CRM setup"
        ]
      },
      {
        "l": "Follow-Up & Reviews",
        "it": [
          "Automated follow-up",
          "Review request automation",
          "Google Maps tracking dashboard"
        ]
      }
    ],
    "kpis": [
      "Phone calls",
      "Quote requests",
      "Cost per roofing lead",
      "Map pack ranking",
      "Service area traffic",
      "Review growth",
      "Form submissions",
      "Booked estimates"
    ],
    "faqs": [
      {
        "q": "How can roofing companies get more leads?",
        "a": "Consistent lead flow comes from ranking well in the Google Maps pack, having a dedicated service area page for every zip code covered, and following up fast with call tracking and CRM automation behind every quote request."
      },
      {
        "q": "Does SEO work for roofing companies?",
        "a": "Yes — local SEO is one of the highest-ROI channels for roofers, since most roofing searches happen with strong local intent (\"roofer near me\", \"roof repair [city]\") that local SEO directly targets."
      },
      {
        "q": "Should roofers run Google Ads?",
        "a": "Google Ads can deliver fast leads for emergency or storm-damage searches, but performs best when paired with call tracking and a fast follow-up process — without that, ad spend is hard to evaluate."
      },
      {
        "q": "Can you build roofing service area pages?",
        "a": "Yes — dedicated landing pages for each city or zip code in your service area are built to rank for hyper-local roofing searches and build trust with homeowners researching contractors."
      },
      {
        "q": "How do you track roofing calls and quote requests?",
        "a": "Call tracking numbers and quote form tracking attribute every lead to its specific source, giving a clear view of which channels are actually generating booked estimates."
      },
      {
        "q": "Do you help with storm-season campaigns?",
        "a": "Yes — a storm-season campaign playbook combining Google Ads, Facebook neighborhood targeting and fast-response messaging is built in advance so you can move quickly when storm damage drives demand."
      },
      {
        "q": "How important are reviews for roofing companies?",
        "a": "Very — review volume and rating are both a strong local ranking signal and a major trust factor for homeowners comparing multiple roofing quotes before deciding."
      },
      {
        "q": "Do you work with both residential and commercial roofers?",
        "a": "Yes — strategy and landing page messaging are adjusted for residential homeowner leads versus commercial property leads, which have meaningfully different buying processes."
      },
      {
        "q": "How fast should we follow up on a roofing quote request?",
        "a": "Industry data consistently shows the fastest-responding contractor wins a disproportionate share of jobs — we build automated CRM follow-up specifically to minimize response time."
      },
      {
        "q": "How quickly can roofing marketing show results?",
        "a": "Google Ads can generate calls within days; local SEO and map pack ranking improvements typically take 60-90 days to compound — we set realistic expectations during onboarding."
      },
      {
        "q": "Do you require a long-term contract?",
        "a": "No — month-to-month engagements with no lock-in contract, reported against calls and quote requests generated."
      }
    ],
    "relatedServices": [
      "localseo",
      "gbp",
      "sem"
    ],
    "relatedIndustries": [
      "realestate",
      "healthcare",
      "law"
    ]
  },
  "healthcare": {
    "eye": "HEALTHCARE & WELLNESS MARKETING",
    "emoji": "🏥",
    "h1": "Patient acquisition and practice growth for healthcare providers.",
    "sub": "HIPAA-aware digital marketing for healthcare providers, medical practices and wellness brands — patient acquisition, local SEO and compliant content marketing that builds trust and drives appointments.",
    "ctaLabel": "Get Started",
    "problems": [
      "Low clinic visibility",
      "Weak treatment or service pages",
      "Poor appointment booking conversion",
      "Trust and review gaps",
      "Healthcare content not written with authority",
      "Ad compliance concerns",
      "No patient follow-up system",
      "Poor provider profile pages"
    ],
    "buildIntro": "Healthcare marketing carries a higher trust bar than most industries — a ranking treatment page with a clunky booking flow, or an ad campaign that isn't compliance-aware, both cost patients. We build E-E-A-T-grounded content and booking systems together, with privacy-aware form handling throughout.",
    "buildAssets": [
      "An online appointment booking system",
      "Patient intake forms with privacy-aware handling",
      "Doctor and provider profile pages",
      "Review request automation",
      "Schema and E-E-A-T content structure",
      "An AI chatbot for general FAQs (not medical diagnosis)"
    ],
    "serviceGrid": [
      {
        "id": "localseo",
        "ico": "📍",
        "n": "Healthcare Local SEO",
        "d": "Rank for high-value local medical queries — \"dentist near me\", \"physiotherapist [city]\", \"urgent care [neighborhood]\" — capturing patients at the moment of need."
      },
      {
        "id": "gbp",
        "ico": "📌",
        "n": "Healthcare Google Business Profile",
        "d": "GBP optimization for medical practices — appointment booking integration, service listings, photo management and review acquisition strategy."
      },
      {
        "id": "seo",
        "ico": "🔍",
        "n": "Medical YMYL SEO",
        "d": "E-E-A-T compliant healthcare content that satisfies Google's Your Money Your Life standards — building search visibility without risking ranking penalties."
      },
      {
        "id": "content",
        "ico": "✍️",
        "n": "Healthcare Content Marketing",
        "d": "Medically accurate, privacy-aware content that educates patients, builds practitioner authority and ranks for condition and treatment-related searches."
      },
      {
        "id": "sem",
        "ico": "💰",
        "n": "Healthcare Google Ads",
        "d": "Compliant Google Ads for medical practices — targeted campaigns capturing high-intent patients searching for your specific services in your area."
      },
      {
        "id": "geo",
        "ico": "🤖",
        "n": "Healthcare GEO / AEO",
        "d": "Get your practice recommended in ChatGPT and Google AI answers when patients ask health questions — AI answer engine presence most healthcare providers haven't addressed."
      }
    ],
    "funnel": [
      "Local Search / Maps",
      "Treatment / Service Page",
      "Appointment Booking Form",
      "Patient Intake",
      "Automated Reminder",
      "Review Request",
      "Retargeting"
    ],
    "techStack": [
      {
        "l": "Website & Booking",
        "it": [
          "Clinic website development",
          "Appointment booking system",
          "Patient intake forms"
        ]
      },
      {
        "l": "Trust & Compliance",
        "it": [
          "Privacy-aware form handling",
          "Schema & E-E-A-T content",
          "Review automation"
        ]
      },
      {
        "l": "Engagement",
        "it": [
          "AI chatbot for general FAQs",
          "Analytics dashboard"
        ]
      }
    ],
    "kpis": [
      "Appointments booked",
      "Cost per appointment",
      "Phone calls",
      "Form submissions",
      "Local rankings",
      "Review growth",
      "Treatment page traffic",
      "Patient inquiry rate"
    ],
    "faqs": [
      {
        "q": "Can you help clinics get more appointments?",
        "a": "Yes — local SEO, optimized treatment pages and a streamlined booking flow work together to convert more searchers into booked appointments, rather than relying on visibility alone."
      },
      {
        "q": "Do you create healthcare service pages?",
        "a": "Yes — dedicated pages for each treatment or service are built with E-E-A-T-grounded content that satisfies Google's standards for medical/health content while clearly explaining what patients can expect."
      },
      {
        "q": "Can you run ads for healthcare businesses?",
        "a": "Yes — Google Ads for healthcare requires navigating specific advertising policies; we build compliant campaigns that meet platform requirements while still capturing high-intent patient searches."
      },
      {
        "q": "How do you handle patient trust and reviews?",
        "a": "A structured, compliant review request workflow after appointments, combined with authoritative content and clear provider profiles, builds the trust signals patients look for when choosing a provider."
      },
      {
        "q": "Can you build appointment booking systems?",
        "a": "Yes — booking system integration with automated reminders and patient intake forms is a core technology deliverable for healthcare clients."
      },
      {
        "q": "Do you handle patient data in a privacy-aware way?",
        "a": "Yes — form handling and data processes are built with privacy and regional compliance requirements (such as HIPAA in the US) in mind; we are not a legal compliance authority and recommend clients confirm specific regulatory requirements with their own counsel."
      },
      {
        "q": "Do you work with wellness brands as well as medical clinics?",
        "a": "Yes — wellness brands (fitness, nutrition, mental health, spa and wellness services) are supported alongside traditional medical practices, with messaging adjusted to each category's regulatory environment."
      },
      {
        "q": "Can your AI chatbot answer medical questions?",
        "a": "No — any chatbot we build for healthcare clients is scoped to general FAQs (hours, services, booking) rather than medical diagnosis or advice, which should always come from a licensed provider."
      },
      {
        "q": "How important is GEO/AEO for healthcare providers?",
        "a": "Increasingly important — patients are starting to ask AI tools health-related questions before searching Google directly, making AI answer engine visibility a growing channel for patient discovery."
      },
      {
        "q": "How quickly can healthcare marketing show results?",
        "a": "Local SEO and Google Business Profile improvements typically show movement within 60-90 days; we set a realistic timeline specific to your market and competition during onboarding."
      },
      {
        "q": "Do you require a long-term contract?",
        "a": "No — month-to-month engagements with no lock-in, reported against appointments booked and cost per appointment."
      }
    ],
    "relatedServices": [
      "localseo",
      "sem",
      "chatbot"
    ],
    "relatedIndustries": [
      "law",
      "fintech",
      "nonprofit"
    ]
  },
  "restaurant": {
    "eye": "RESTAURANT & FOOD SERVICE MARKETING",
    "emoji": "🍽️",
    "h1": "Fill more tables and grow your restaurant with proven digital marketing.",
    "sub": "Local SEO, Google Maps domination, social media management and reputation management — marketing systems that drive consistent foot traffic, reservations and online orders for restaurants, cafes, bars and food businesses.",
    "ctaLabel": "Get Started",
    "problems": [
      "Weak Google Maps visibility",
      "Menu not optimized for search",
      "Poor online ordering funnel",
      "Low delivery platform visibility",
      "Few reviews compared with competitors",
      "No loyalty or SMS system",
      "Inconsistent social content",
      "No catering or event landing pages"
    ],
    "buildIntro": "Beautiful food photography with no online ordering funnel behind it, or strong Maps visibility with a clunky reservation flow, both leave covers on the table — we connect discovery, ordering and loyalty into one system built around how diners actually search and order.",
    "buildAssets": [
      "An online ordering and reservation system",
      "Menu landing pages optimized for search",
      "A loyalty and SMS promotion system",
      "WhatsApp ordering setup where relevant",
      "Catering and event landing pages",
      "Google Business Profile setup with menu integration"
    ],
    "serviceGrid": [
      {
        "id": "localseo",
        "ico": "📍",
        "n": "Restaurant Local SEO",
        "d": "Dominate \"restaurants near me\", \"best [cuisine] in [city]\" and Google Maps results — capturing hungry customers at the exact moment they search."
      },
      {
        "id": "gbp",
        "ico": "📌",
        "n": "Google Business Profile",
        "d": "Fully optimized GBP with menu integration, photo management, review acquisition and weekly posts — the #1 driver of restaurant foot traffic from Google."
      },
      {
        "id": "smmanage",
        "ico": "📱",
        "n": "Social Media Management",
        "d": "Mouth-watering food photography content, daily posting, community management and influencer seeding — building the social presence that fills seats."
      },
      {
        "id": "fbads",
        "ico": "📣",
        "n": "Facebook & Instagram Ads",
        "d": "Geo-targeted ads reaching hungry local customers — promoting daily specials, events, new menus and online ordering with measurable foot traffic attribution."
      },
      {
        "id": "influencer",
        "ico": "⭐",
        "n": "Food Influencer Marketing",
        "d": "Local food bloggers, Instagram creators and TikTok food accounts driving authentic awareness — the most trusted form of restaurant discovery for new customers."
      },
      {
        "id": "content",
        "ico": "✍️",
        "n": "Reputation Management",
        "d": "Review generation strategy, professional response to all Google and TripAdvisor reviews and reputation monitoring — building the rating that drives reservations."
      }
    ],
    "funnel": [
      "Google Maps / Social Discovery",
      "Menu / Profile View",
      "Reservation or Online Order",
      "Loyalty / SMS Signup",
      "Repeat Visit",
      "Review Request",
      "Referral"
    ],
    "techStack": [
      {
        "l": "Ordering & Booking",
        "it": [
          "Online ordering system",
          "Reservation system",
          "WhatsApp ordering"
        ]
      },
      {
        "l": "Visibility",
        "it": [
          "Google Business Profile setup",
          "Menu landing pages"
        ]
      },
      {
        "l": "Retention",
        "it": [
          "Loyalty and SMS system",
          "Analytics dashboard"
        ]
      }
    ],
    "kpis": [
      "Reservations",
      "Online orders",
      "Delivery orders",
      "Foot traffic",
      "Google Maps views",
      "Review growth",
      "Repeat customers",
      "SMS/email campaign revenue"
    ],
    "faqs": [
      {
        "q": "How can restaurants get more customers online?",
        "a": "Strong Google Maps visibility combined with an optimized menu, easy online ordering and active social content together drive the consistent discovery and conversion most restaurants need — any one alone tends to underperform."
      },
      {
        "q": "Do you help with Google Maps ranking?",
        "a": "Yes — Google Business Profile optimization, including menu integration, photos and review generation, is one of the highest-impact channels for restaurant visibility."
      },
      {
        "q": "Can you build online ordering pages?",
        "a": "Yes — menu landing pages and online ordering funnel optimization are built to reduce friction between a hungry searcher and a completed order."
      },
      {
        "q": "Do TikTok and Instagram work for restaurants?",
        "a": "Yes — food content performs strongly on both platforms, and consistent short-form video alongside influencer seeding is one of the most effective ways to build authentic local awareness."
      },
      {
        "q": "Can you help with delivery and catering promotion?",
        "a": "Yes — delivery platform visibility strategy and dedicated catering/event landing pages are built to capture demand beyond standard dine-in traffic."
      },
      {
        "q": "How important are reviews for restaurants?",
        "a": "Very — review volume and rating directly affect both Google Maps ranking and a diner's decision to choose your restaurant over a nearby competitor with similar offerings."
      },
      {
        "q": "Do you set up loyalty or SMS marketing for restaurants?",
        "a": "Yes — a loyalty and SMS/email promotion system is a core deliverable, used to drive repeat visits from existing customers rather than relying solely on new customer acquisition."
      },
      {
        "q": "Can you help with WhatsApp ordering?",
        "a": "Yes — WhatsApp Business ordering setup is available where relevant to your market, particularly useful for delivery-focused restaurants in regions with high WhatsApp usage."
      },
      {
        "q": "Do you work with cafes and bars, not just full-service restaurants?",
        "a": "Yes — cafes, bars, food trucks and quick-service concepts are all supported, with strategy adjusted to each format's typical customer journey."
      },
      {
        "q": "How quickly can restaurant marketing show results?",
        "a": "Google Business Profile and social content improvements often show movement within 30-60 days; we set realistic timelines based on your market and current online presence during onboarding."
      },
      {
        "q": "Do you require a long-term contract?",
        "a": "No — month-to-month engagements with no lock-in, reported against reservations, orders and foot traffic."
      }
    ],
    "relatedServices": [
      "localseo",
      "smmanage",
      "sms"
    ],
    "relatedIndustries": [
      "realestate",
      "nonprofit",
      "roofing"
    ]
  },
  "nonprofit": {
    "eye": "NONPROFIT & CHARITY MARKETING",
    "emoji": "💛",
    "h1": "Amplify your mission — reach more donors, volunteers and supporters.",
    "sub": "Nonprofit-specific SEO, Google Ad Grants management, social media campaigns and donation funnel optimization — helping nonprofits and charities maximize their digital presence and fundraising impact.",
    "ctaLabel": "Get Started",
    "problems": [
      "Low donation conversion",
      "Weak storytelling",
      "Poor donor retention",
      "No email nurture sequence",
      "Limited campaign visibility",
      "No volunteer recruitment funnel",
      "Weak impact reporting",
      "Poor event promotion"
    ],
    "buildIntro": "Powerful mission storytelling with no donation page optimization, or strong campaign reach with no donor retention follow-up, both leave impact on the table — we connect awareness, conversion and retention into one donor journey.",
    "buildAssets": [
      "Donation landing pages with payment integration",
      "A donor CRM / management integration",
      "Email donor nurture automation",
      "Volunteer sign-up forms",
      "An impact reporting dashboard",
      "An AI chatbot for donor questions"
    ],
    "serviceGrid": [
      {
        "id": "sem",
        "ico": "💰",
        "n": "Google Ad Grants Management",
        "d": "We manage your monthly Google Ad Grants account to drive maximum qualified traffic for donor acquisition, volunteer recruitment and cause awareness."
      },
      {
        "id": "seo",
        "ico": "🔍",
        "n": "Nonprofit SEO",
        "d": "Rank for cause-related search terms, donor intent keywords and volunteer recruitment queries — building organic visibility that compounds over time."
      },
      {
        "id": "content",
        "ico": "✍️",
        "n": "Impact Content Marketing",
        "d": "Storytelling content — impact reports, beneficiary stories, volunteer spotlights — that builds emotional connection and drives recurring donor retention."
      },
      {
        "id": "emailauto",
        "ico": "🔄",
        "n": "Donor Email Automation",
        "d": "Welcome sequences, impact updates, donation reminders and re-engagement campaigns — nurturing one-time donors into recurring supporters automatically."
      },
      {
        "id": "smm",
        "ico": "📱",
        "n": "Social Media for Nonprofits",
        "d": "Mission-driven social media strategy building community, sharing impact stories and mobilizing supporters across Facebook, Instagram, TikTok and LinkedIn."
      },
      {
        "id": "cro",
        "ico": "📈",
        "n": "Donation Page Optimization",
        "d": "A/B testing and CRO for donation pages, volunteer signup forms and event registration — increasing the percentage of visitors who take action."
      }
    ],
    "funnel": [
      "Campaign / PR Visibility",
      "Donation or Volunteer Landing Page",
      "Donation Form / Signup",
      "Donor CRM",
      "Email Nurture",
      "Impact Update",
      "Recurring Donation"
    ],
    "techStack": [
      {
        "l": "Donation & Forms",
        "it": [
          "Donation landing pages",
          "Payment integration",
          "Volunteer sign-up forms"
        ]
      },
      {
        "l": "Donor Management",
        "it": [
          "CRM / donor management integration",
          "Email automation"
        ]
      },
      {
        "l": "Reporting & Engagement",
        "it": [
          "Impact dashboard",
          "AI chatbot for donor questions",
          "Campaign reporting dashboard"
        ]
      }
    ],
    "kpis": [
      "Donations",
      "Donation conversion rate",
      "Donor retention",
      "Volunteer signups",
      "Campaign reach",
      "Email open/click rate",
      "Event registrations",
      "Cost per donor"
    ],
    "faqs": [
      {
        "q": "Can you help nonprofits raise donations?",
        "a": "Yes — we combine SEO, Google Ad Grants management and donation page optimization with donor email nurture, since awareness alone rarely converts without a frictionless donation flow and follow-up behind it."
      },
      {
        "q": "Do you build donation landing pages?",
        "a": "Yes — conversion-focused donation pages with integrated payment processing are a core deliverable, built to reduce drop-off between intent and completed donation."
      },
      {
        "q": "Can you help with Google Ad Grants?",
        "a": "Yes — Google Ad Grants management for eligible nonprofits is a core service, used to drive qualified traffic for donor acquisition and volunteer recruitment using the nonprofit's monthly grant."
      },
      {
        "q": "How do you improve donor retention?",
        "a": "Donor retention improves through structured email nurture (welcome sequences, impact updates, timely donation reminders) and transparent impact reporting that shows donors the result of their support."
      },
      {
        "q": "Do you support charity campaign storytelling?",
        "a": "Yes — impact content marketing including beneficiary stories, volunteer spotlights and impact reports is built to create the emotional connection that drives both first-time and recurring donations."
      },
      {
        "q": "Can you help with volunteer recruitment, not just donations?",
        "a": "Yes — volunteer recruitment funnels, including dedicated landing pages and sign-up forms, are built alongside donation-focused campaigns."
      },
      {
        "q": "Do you work with small, locally-based nonprofits?",
        "a": "Yes — nonprofits of every size are supported, with scope and channel mix tailored to your budget and current digital presence."
      },
      {
        "q": "How do you measure success for nonprofit marketing?",
        "a": "Donations, donor retention rate, volunteer signups and campaign reach are the core metrics tracked, alongside cost per donor to evaluate channel efficiency."
      },
      {
        "q": "Can you help with peer-to-peer fundraising campaigns?",
        "a": "Yes — peer-to-peer fundraising strategy and supporting landing pages are available as part of broader donation campaign strategy."
      },
      {
        "q": "Is Google Ad Grants free advertising for any nonprofit?",
        "a": "Eligible 501(c)(3) nonprofits (or equivalent in other countries) can receive in-kind Google Search advertising credit through the Ad Grants program — eligibility and program rules are set by Google, and we help manage the account once approved."
      },
      {
        "q": "Do you require a long-term contract?",
        "a": "No — month-to-month engagements with no lock-in, reported against donations and donor retention."
      }
    ],
    "relatedServices": [
      "email",
      "digitalpr",
      "crm"
    ],
    "relatedIndustries": [
      "healthcare",
      "restaurant",
      "course"
    ]
  },
  "fintech": {
    "eye": "FINANCE & FINTECH MARKETING",
    "emoji": "💰",
    "h1": "Compliant, high-performance digital marketing for finance and fintech brands.",
    "sub": "YMYL-aware SEO, compliant paid advertising, GEO/AEO for AI financial queries and content marketing — driving qualified customer acquisition for banks, fintechs, investment platforms, insurance brands and financial advisors.",
    "ctaLabel": "Get Started",
    "problems": [
      "Low trust in financial offers",
      "Compliance-sensitive messaging constraints",
      "Weak educational content",
      "Expensive lead generation",
      "Poor fintech app visibility",
      "No investor positioning",
      "Weak retargeting and nurture",
      "No structured authority content"
    ],
    "buildIntro": "Financial marketing carries strict compliance and trust requirements most generalist agencies underestimate — a high-ranking page with non-compliant claims, or a strong app install campaign with no secure landing page behind it, both create risk. We build authority content and conversion systems with regulatory-safe messaging from the start.",
    "buildAssets": [
      "Secure, compliance-friendly landing pages",
      "Compliance-friendly form handling",
      "CRM integration for application tracking",
      "App analytics for fintech apps",
      "A trust and credibility content system",
      "An AI chatbot for general product questions"
    ],
    "serviceGrid": [
      {
        "id": "seo",
        "ico": "🔍",
        "n": "YMYL Financial SEO",
        "d": "E-E-A-T compliant SEO for finance — ranking for high-value money and investment keywords while meeting Google's strict Your Money Your Life content standards."
      },
      {
        "id": "geo",
        "ico": "🤖",
        "n": "GEO/AEO for Finance",
        "d": "Get your brand recommended in ChatGPT and Google AI answers when users ask financial questions — the fastest-growing discovery channel for fintech brands."
      },
      {
        "id": "content",
        "ico": "✍️",
        "n": "Financial Content Marketing",
        "d": "Expert financial content — guides, calculators, market commentary and educational resources — building the E-E-A-T signals that Google and AI models reward."
      },
      {
        "id": "linkedinads",
        "ico": "💼",
        "n": "LinkedIn Ads for Fintech",
        "d": "B2B fintech advertising reaching CFOs, finance directors and investment decision-makers — with compliant messaging and high-quality lead generation."
      },
      {
        "id": "sem",
        "ico": "💰",
        "n": "Compliant Google Ads",
        "d": "Certified, policy-compliant Google Ads for financial services — navigating Google's financial product advertising policies to maximize visibility and conversions."
      },
      {
        "id": "crm",
        "ico": "⚙️",
        "n": "Fintech Marketing Automation",
        "d": "Lead nurturing, onboarding sequences, product activation campaigns and lifecycle marketing — converting sign-ups into active, revenue-generating customers."
      }
    ],
    "funnel": [
      "Search / LinkedIn Discovery",
      "Trust / Education Page",
      "Application or Demo Start",
      "CRM Tracking",
      "Compliance-Safe Nurture",
      "Activation",
      "Retargeting"
    ],
    "techStack": [
      {
        "l": "Website & Forms",
        "it": [
          "Fintech website development",
          "Secure landing pages",
          "Compliance-friendly forms"
        ]
      },
      {
        "l": "Tracking & Integration",
        "it": [
          "CRM integration",
          "App analytics",
          "API integration support"
        ]
      },
      {
        "l": "Trust & Engagement",
        "it": [
          "Dashboard reporting",
          "AI chatbot for general product questions"
        ]
      }
    ],
    "kpis": [
      "Qualified finance leads",
      "App installs",
      "Cost per lead",
      "Demo bookings",
      "Application starts",
      "Trust page engagement",
      "Organic traffic",
      "Investor inquiries"
    ],
    "faqs": [
      {
        "q": "Can you market fintech apps?",
        "a": "Yes — fintech app growth combining ASO-adjacent visibility, compliant paid acquisition and secure landing pages is a core part of this service, with app analytics tracking install-to-activation."
      },
      {
        "q": "How do you handle compliance-sensitive financial content?",
        "a": "Content is built with regulatory-safe messaging — avoiding guaranteed-return language, unverified claims or anything that could be read as financial advice — while still being genuinely educational and trust-building."
      },
      {
        "q": "Do you create finance landing pages?",
        "a": "Yes — secure, compliance-friendly landing pages with appropriate form handling are built specifically for financial product applications, demos or lead capture."
      },
      {
        "q": "Can you help with investor visibility?",
        "a": "Yes — credibility and investor-facing positioning content, alongside PR and thought leadership, are available for fintech companies building visibility with both customers and the investment community."
      },
      {
        "q": "How do you track fintech leads and conversions?",
        "a": "CRM integration tracks leads from first touch through application or demo, giving visibility into which channels are producing qualified, compliant pipeline rather than just raw traffic."
      },
      {
        "q": "Is Google Ads allowed for financial services companies?",
        "a": "Yes, within Google's specific financial products and services advertising policies — certification and policy-compliant campaign structure are required, which we manage as part of the service."
      },
      {
        "q": "Do you work with banks as well as fintech startups?",
        "a": "Yes — both established financial institutions and early-stage fintech startups are supported, with messaging and compliance rigor adjusted to your specific regulatory environment."
      },
      {
        "q": "What is GEO/AEO and why does it matter for finance?",
        "a": "GEO/AEO optimizes for citation inside AI-generated answers from tools like ChatGPT and Google AI Overviews — increasingly relevant as users ask AI tools financial questions before searching Google directly."
      },
      {
        "q": "Can you help with LinkedIn Ads for B2B fintech?",
        "a": "Yes — LinkedIn Ads targeting CFOs, finance directors and investment decision-makers is a core channel for B2B fintech products, with compliant messaging built into every campaign."
      },
      {
        "q": "How quickly can fintech marketing show results?",
        "a": "Paid campaigns can generate qualified leads within weeks; SEO and content authority-building for competitive financial keywords typically take 4-6 months — we set realistic expectations during onboarding."
      },
      {
        "q": "Do you require a long-term contract?",
        "a": "No — month-to-month engagements with no lock-in, reported against qualified leads and application starts rather than vanity traffic."
      }
    ],
    "relatedServices": [
      "geo",
      "linkedinads",
      "chatbot"
    ],
    "relatedIndustries": [
      "saas",
      "law",
      "healthcare"
    ]
  }
};
